version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      backend-minor-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(backend deps)"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      frontend-minor-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(frontend deps)"

  - package-ecosystem: "npm"
    directory: "/database"
    schedule:
      interval: "weekly"
    groups:
      database-minor-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(database deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci deps)"
