import { createContext, useContext, useState, useCallback, useMemo, useEffect } from "react";
import { setFormatLocale } from "../utils/format";

const LanguageContext = createContext(null);

const STORAGE_KEY = "nexora_language";
export const LANGUAGES = [
    { code: "en", label: "English" },
    { code: "sw", label: "Kiswahili" }
];


export const DICTIONARY = {
    en: {
        "nav.home": "Home",
        "nav.dashboard": "Dashboard",
        "nav.deliveries": "Deliveries",
        "nav.admin": "Admin",
        "nav.messages": "Messages",
        "nav.orders": "Orders",
        "nav.bookings": "Bookings",
        "nav.disputes": "Disputes",
        "nav.returns": "Returns",
        "nav.saved": "Saved",
        "nav.wallet": "Wallet",
        "nav.cart": "Cart",
        "nav.account": "Account",
        "nav.browse": "Browse all",
        "nav.services": "Services",
        "nav.signOut": "Sign out",
        "nav.signIn": "Sign in",
        "nav.join": "Join",
        "nav.searchPlaceholder": "Search products, brands...",
        "nav.search": "Search",
        "nav.go": "Go",

        "search.recent": "Recent searches",
        "search.clearRecent": "Clear",
        "search.resultsFor": "Results for \"{term}\"",
        "search.resultCountOne": "1 result",
        "search.resultCountMany": "{count} results",
        "search.clearSearch": "Clear search",
        "search.noResultsTitle": "No results for \"{term}\"",
        "search.noResultsHint": "Try a different search term, check your spelling, or browse a department instead.",
        "search.browseDepartments": "Browse departments",
        "search.browseAll": "Browse all products",

        "filters.minPrice": "Min price",
        "filters.maxPrice": "Max price",
        "filters.noLimit": "No limit",
        "filters.store": "Store",
        "filters.allStores": "All stores",
        "filters.location": "Location",
        "filters.allLocations": "All locations",
        "filters.rating": "Rating",
        "filters.anyRating": "Any rating",
        "filters.andUp": "& up",
        "filters.sortBy": "Sort by",
        "filters.sortNewest": "Newest",
        "filters.sortPriceLow": "Price: low to high",
        "filters.sortPriceHigh": "Price: high to low",
        "filters.sortRating": "Highest rated",
        "filters.clear": "Clear filters",

        "products.viewGrid": "Grid view",
        "products.viewList": "List view",

        "account.title": "Account",
        "account.signedInAs": "Signed in as",
        "account.profile": "Profile",
        "account.settings": "Settings",
        "account.settingsHint": "Language, theme, and currency apply across NEXORA instantly.",
        "account.language": "Language",
        "account.theme": "Theme",
        "account.currency": "Currency",
        "account.changePassword": "Change password",
        "account.changePasswordHint": "For your security, we'll email you a verification code before you can set a new password.",
        "account.changePasswordButton": "Change Password",
        "account.deleteAccount": "Delete account",

        "common.save": "Save",
        "common.saving": "Saving…",
        "common.cancel": "Cancel",
        "common.continue": "Continue",
        "common.loading": "Loading…",
        "common.remove": "Remove",
        "common.each": "each",
        "common.total": "Total",
        "common.browseMarketplace": "Browse the marketplace",
        "common.startShopping": "Start shopping",
        "common.somethingWentWrong": "Something went wrong. Please try again.",

        "auth.signInTitle": "Sign in",
        "auth.emailLabel": "Email",
        "auth.passwordLabel": "Password",
        "auth.signInButton": "Sign in",
        "auth.signingIn": "Signing in…",
        "auth.noAccount": "Don't have an account?",
        "auth.registerLink": "Create one",
        "auth.forgotPasswordLink": "Forgot your password?",
        "auth.registerTitle": "Create your account",
        "auth.haveAccount": "Already have an account?",
        "auth.signInLink": "Sign in",
        "auth.registerSubtitle": "Create your account to start buying, selling, or delivering.",
        "auth.firstNameLabel": "First name",
        "auth.lastNameLabel": "Last name",
        "auth.phoneLabel": "Phone",
        "auth.phoneHint": "Choose your country, then enter your number without the leading 0.",
        "auth.countryCodeLabel": "Country code",
        "auth.passwordHint": "At least 8 characters.",
        "auth.roleLabel": "I want to",
        "auth.roleBuyer": "Buy products",
        "auth.roleSeller": "Sell products",
        "auth.roleDeliveryAgent": "Deliver orders",
        "auth.roleVerificationHint": "You'll be asked to verify your identity on the next step before your account is created.",
        "auth.termsPrefix": "I agree to NEXORA's",
        "auth.termsOfService": "Terms of Service",
        "auth.and": "and",
        "auth.privacyPolicy": "Privacy Policy",
        "auth.createAccountButton": "Create account",
        "auth.creatingAccount": "Creating account…",
        "auth.continueToVerification": "Continue to verification",
        "auth.termsRequiredError": "Please accept the Terms of Service and Privacy Policy to continue.",
        "auth.invalidPhoneError": "Please enter a valid phone number.",

        "cart.title": "Your cart",
        "cart.empty": "Your cart is empty",
        "cart.loading": "Loading cart…",
        "cart.checkoutButton": "Proceed to checkout",

        "checkout.title": "Checkout",
        "checkout.placeOrderButton": "Place order",
        "checkout.placingOrder": "Placing order…",
        "checkout.streetAddress": "Street address",
        "checkout.city": "City",
        "checkout.region": "Region",
        "checkout.contactPhone": "Contact phone",
        "checkout.paymentMethod": "Payment method",
        "checkout.orderSummary": "Order summary",
        "checkout.buyerProtection.title": "Buyer Protection",
        "checkout.buyerProtection.description": "Extends your return window to 14 days and guarantees a refund if something goes wrong",

        "return.new.pageTitle": "Request a return",
        "return.new.eyebrow": "Buyer Protection",
        "return.new.intro": "Tell us what happened and we'll review your request.",
        "return.new.itemLabel": "Item",
        "return.new.wholeOrderOption": "Whole order",
        "return.new.reasonLabel": "Reason",
        "return.new.detailsLabel": "Details (optional)",
        "return.new.detailsPlaceholder": "Anything the seller should know",
        "return.new.submit": "Submit return request",
        "return.new.submitting": "Submitting…",
        "return.new.cancel": "Cancel",
        "return.new.noOrderSpecified": "No order specified",
        "return.new.loadErrorTitle": "Couldn't load this order",
        "return.new.backToOrders": "Back to orders",
        "return.reason.damaged_item": "Item arrived damaged",
        "return.reason.wrong_item": "Wrong item received",
        "return.reason.defective_product": "Product is defective",
        "return.reason.not_as_described": "Not as described",
        "return.reason.changed_mind": "Changed my mind",
        "return.reason.other": "Other",

        "returns.title": "Your returns",
        "returns.empty": "No return requests yet",
        "returns.loading": "Loading returns…",

        "orders.title": "Your orders",
        "orders.empty": "No orders yet",
        "orders.loading": "Loading orders…",
        "orders.vendorsBadge": "{count} vendors",

        "orderTimeline.placed": "Placed",
        "orderTimeline.processing": "Processing",
        "orderTimeline.shipped": "Shipped",
        "orderTimeline.delivered": "Delivered",
        "orderTimeline.cancelled": "This order was cancelled.",

        "delivery.tracking.title": "Delivery tracking",
        "delivery.tracking.agentEnRoute": "Your delivery agent is on the way",
        "delivery.tracking.awaitingAgent": "Waiting for a delivery agent",
        "delivery.tracking.eta": "Estimated arrival",
        "delivery.tracking.viewLive": "View live tracking",
        "delivery.tracking.live": "Live",
        "delivery.tracking.connecting": "Connecting…",
        "delivery.tracking.reconnecting": "Reconnecting…",
        "delivery.tracking.offline": "Tracking unavailable — check your connection",
        "delivery.tracking.distanceRemaining": "Distance remaining",
        "delivery.tracking.calculating": "Calculating…",
        "delivery.tracking.back": "Back to order",
        "delivery.tracking.unavailable": "Tracking unavailable",        "delivery.tracking.pickup": "Pickup",
        "delivery.tracking.destination": "Destination",
        "delivery.tracking.viewFullscreen": "View fullscreen",
        "delivery.tracking.exitFullscreen": "Exit fullscreen",
        "delivery.tracking.courierDetails": "Courier details",
        "delivery.tracking.messageCourier": "Message",
        "delivery.tracking.callCourier": "Call",
        "delivery.tracking.timeline.title": "Delivery timeline",
        "delivery.tracking.timeline.assigned": "Agent assigned",
        "delivery.tracking.timeline.picked_up": "Picked up",
        "delivery.tracking.timeline.in_transit": "On the way",
        "delivery.tracking.timeline.delivered": "Delivered",
        "delivery.tracking.timeline.failed": "Delivery failed",

        "delivery.agent.available.empty": "No orders ready for pickup right now. Check back soon.",
        "delivery.agent.available.claimed": "Order claimed — find it under My deliveries.",
        "delivery.agent.available.claim": "Claim",
        "delivery.agent.available.claiming": "Claiming…",
        "delivery.agent.mine.empty": "You haven't claimed any deliveries yet.",
        "delivery.agent.mine.contact": "Contact",
        "delivery.agent.mine.markPickedUp": "Mark picked up",
        "delivery.agent.mine.markInTransit": "Mark in transit",
        "delivery.agent.mine.markDelivered": "Mark delivered",
        "delivery.agent.mine.reportFailed": "Report failed",
        "delivery.agent.earnings.title": "Earnings",
        "delivery.agent.earnings.subtitle": "What you've earned delivering for NEXORA.",
        "delivery.agent.earnings.totalEarned": "Total earned",
        "delivery.agent.earnings.today": "Today",
        "delivery.agent.earnings.last7Days": "Last 7 days",
        "delivery.agent.earnings.last30Days": "Last 30 days",
        "delivery.agent.earnings.chartTitle": "Earnings - last 14 days",
        "delivery.agent.earnings.deliveriesTotal": "deliveries total",
        "delivery.agent.earnings.recent": "Recent deliveries",
        "delivery.agent.earnings.noRecent": "No completed deliveries yet.",
        "delivery.agent.earnings.loadError": "Couldn't load your earnings.",
        "delivery.agent.ratings.title": "Ratings",
        "delivery.agent.ratings.subtitle": "What buyers have said about your deliveries.",
        "delivery.agent.ratings.average": "Average rating",
        "delivery.agent.ratings.none": "No ratings yet",
        "delivery.agent.ratings.total": "Total ratings",
        "delivery.agent.ratings.recent": "Recent ratings",
        "delivery.agent.ratings.noRecent": "No ratings yet - they'll show up here after buyers rate a delivered order.",
        "delivery.agent.ratings.loadError": "Couldn't load your ratings.",

        "dispute.type.damaged_item": "Damaged item",
        "dispute.type.delayed_delivery": "Delayed delivery",
        "dispute.type.defective_product": "Defective product",
        "dispute.type.wrong_item": "Wrong item",
        "dispute.type.missing_delivery": "Missing delivery",
        "dispute.type.other": "Other issue",
        "dispute.status.open": "open",
        "dispute.status.under_review": "under review",
        "dispute.status.resolved": "resolved",
        "dispute.status.rejected": "rejected",
        "dispute.status.withdrawn": "withdrawn",

        "dispute.new.eyebrow": "Report a problem",
        "dispute.new.pageTitle": "Report a Problem",
        "dispute.new.intro": "Tell us what went wrong. Our team will review it and reach out with a decision.",
        "dispute.new.loadErrorTitle": "Couldn't load that order",
        "dispute.new.noOrderSpecified": "No order was specified.",
        "dispute.new.backToOrders": "Back to orders",
        "dispute.new.itemLabel": "Which item is this about?",
        "dispute.new.wholeOrderOption": "The whole order (e.g. delayed / missing delivery)",
        "dispute.new.typeLabel": "What's the issue?",
        "dispute.new.selectCategory": "Select a category",
        "dispute.new.subjectLabel": "Subject",
        "dispute.new.subjectPlaceholder": "e.g. Blender arrived with a cracked jug",
        "dispute.new.detailsLabel": "Details",
        "dispute.new.detailsPlaceholder": "Describe what happened. You can attach photos after submitting.",
        "dispute.new.submitting": "Submitting…",
        "dispute.new.submit": "Submit dispute",
        "dispute.new.cancel": "Cancel",

        "dispute.list.title": "My disputes",
        "dispute.list.intro": "Report a problem with any order from its order page, and track the outcome here.",
        "dispute.list.empty": "You haven't filed any disputes.",
        "dispute.list.goToOrders": "Go to your orders",
        "dispute.list.orderPrefix": "Order",
        "dispute.list.refundApproved": "Refund approved",
        "dispute.list.filed": "Filed",
        "dispute.list.maintenanceTitle": "Disputes is under maintenance",

        "dispute.detail.notFound": "Dispute not found",
        "dispute.detail.eyebrow": "Dispute",
        "dispute.detail.onOrder": "On order",
        "dispute.detail.filed": "filed",
        "dispute.detail.evidence": "Evidence",
        "dispute.detail.addPhoto": "+ Add photo",
        "dispute.detail.uploading": "Uploading…",
        "dispute.detail.noPhotos": "No photos attached yet.",
        "dispute.detail.withdraw": "Withdraw dispute",
        "dispute.detail.withdrawing": "Withdrawing…",
        "dispute.detail.withdrawConfirm": "Withdraw this dispute? This can't be undone.",
        "dispute.detail.discussion": "Discussion",
        "dispute.detail.noMessages": "No messages yet.",
        "dispute.detail.replyAs": "Reply as",
        "dispute.detail.sending": "Sending…",
        "dispute.detail.send": "Send",
        "dispute.detail.closedForMessages": "This dispute is closed for new messages.",
        "dispute.detail.resolvedPrefix": "Resolved",
        "dispute.detail.refundAmount": "Refund amount",
        "dispute.detail.rejected": "Dispute rejected",

        "auth.verify.ownerPhotoSeller": "Owner photo / selfie",
        "auth.verify.ownerPhotoDelivery": "Personal photo / selfie",
        "auth.verify.selfieHint": "A clear photo of your face.",
        "auth.verify.idDocument": "National ID or Voter ID",
        "auth.verify.idDocumentHint": "A photo or scan of either document.",
        "auth.verify.driversLicense": "Driver's license",
        "auth.verify.driversLicenseHint": "A photo or scan of your license.",
        "auth.verify.uploadRequired": "Please upload your {label}.",
        "auth.verify.idDocumentRequired": "Please upload your National ID or Voter ID.",
        "auth.verify.plateNumberRequired": "Please enter your vehicle's plate number.",
        "auth.verify.accountCreated": "Account created",
        "auth.verify.pendingReviewNotice": "Your documents were submitted for review. You can sign in now — your dashboard will show \"Pending Review\" until an admin approves your account.",
        "auth.verify.takingToSignIn": "Taking you to sign in…",
        "auth.verify.title": "Verify your identity",
        "auth.verify.introSeller": "Sellers must submit these documents before their account is created. Your account will show as \"Pending Review\" until an admin approves it.",
        "auth.verify.introDeliveryAgent": "Delivery agents must submit these documents before their account is created. Your account will show as \"Pending Review\" until an admin approves it.",
        "auth.verify.idDocTypeLabel": "ID document type",
        "auth.verify.nationalId": "National ID",
        "auth.verify.voterId": "Voter ID",
        "auth.verify.vehicleTypeLabel": "Vehicle type",
        "auth.verify.bicycle": "Bicycle",
        "auth.verify.motorcycle": "Motorcycle",
        "auth.verify.tuktuk": "Tuk-tuk (Bajaji)",
        "auth.verify.car": "Car",
        "auth.verify.van": "Van",
        "auth.verify.truck": "Truck",
        "auth.verify.plateNumberLabel": "Plate number",
        "auth.verify.back": "Back",
        "auth.verify.submitting": "Submitting…",
        "auth.verify.submitForReview": "Submit for review",

        "notifications.title": "Notifications",
        "notifications.empty": "You're all caught up",
        "notifications.markAllRead": "Mark all as read",

        "booking.title": "Your bookings",
        "booking.empty": "No bookings yet",
        "booking.browseServices": "Browse services",
        "booking.loading": "Loading bookings…",
        "booking.reference": "Booking",
        "booking.created": "Created {date}",
        "booking.status.pending": "Pending",
        "booking.status.confirmed": "Confirmed",
        "booking.status.active": "Active",
        "booking.status.completed": "Completed",
        "booking.status.cancelled": "Cancelled",
        "booking.status.refunded": "Refunded",
        "booking.status.rejected": "Rejected",
        "booking.statusLabel": "Status",
        "booking.payment": "Payment",
        "booking.paid": "Paid",
        "booking.unpaid": "Unpaid",
        "booking.checkIn": "Check-in",
        "booking.checkOut": "Check-out",
        "booking.date": "Date",
        "booking.quantity": "Quantity",
        "booking.total": "Total",
        "booking.confirmButton": "Confirm booking",
        "booking.confirming": "Confirming…",
        "booking.cancelButton": "Cancel booking",
        "booking.cancelling": "Cancelling…",
        "booking.rejectButton": "Decline booking",
        "booking.rejecting": "Declining…",
        "booking.rejectedMessage": "Booking declined.",
        "booking.notFound": "Booking not found",
        "booking.backToBookings": "Back to bookings",
        "booking.justBookedTitle": "Booking request sent",
        "booking.justBookedBody": "We've notified {store} — you'll hear back once they confirm.",
        "booking.confirmedMessage": "Booking confirmed.",
        "booking.cancelledMessage": "Booking cancelled.",
        "booking.cancelledRefundedMessage": "Booking cancelled and refunded.",
        "booking.payment.title": "Pay for this booking",
        "booking.payment.escrowNote": "Your payment is held securely until your booking is complete.",
        "booking.payment.phonePlaceholder": "Phone number for mobile money",
        "booking.payment.phoneRequired": "Enter a phone number to pay by mobile money",
        "booking.payment.payMobileMoney": "Pay with Mobile Money",
        "booking.payment.payCard": "Pay with Card (Snippe)",
        "booking.payment.payCardMalipopay": "Pay with Card (MalipoPay)",
        "booking.payment.payPaypal": "Pay with PayPal",
        "booking.payment.processing": "Processing…",
        "booking.payment.redirecting": "Redirecting…",
        "booking.payment.checkPhone": "Check your phone to complete the payment.",
        "booking.payment.confirming": "Confirming your payment…",
        "booking.payment.success": "Payment successful.",
        "booking.payment.notCompleted": "Payment could not be confirmed. Please try again.",
        "booking.payment.stillConfirming": "We're still confirming your payment - this can take a minute. Refresh to check the latest status.",
        "booking.payment.cancelledNotice": "Payment was cancelled - your booking is still saved, you can try paying again below.",
        "booking.progress.title": "Booking progress",
        "booking.progress.pending": "Requested",
        "booking.progress.confirmed": "Confirmed",
        "booking.progress.active": "In progress",
        "booking.progress.completed": "Completed",
        "booking.progress.cancelled": "This booking was cancelled.",
        "booking.progress.refunded": "This booking was refunded.",
        "booking.progress.rejected": "This booking was declined by the provider.",
        "booking.seller.title": "Bookings",
        "booking.seller.onlyProviders": "Bookings management is for service providers. Add services to your store first.",
        "booking.seller.goToServices": "Go to Services",
        "booking.seller.empty": "No bookings yet.",
        "booking.seller.confirm": "Confirm",
        "booking.seller.reject": "Reject",
        "booking.seller.cancel": "Cancel",
        "booking.seller.details": "Details",
        "booking.widget.selectDates": "Select check-in and check-out dates",
        "booking.widget.selectDate": "Select a date",
        "booking.widget.signInPrompt": "Sign in to book this service",
        "booking.widget.signIn": "Sign in",
        "booking.widget.checkInSelected": "Check-in {date} selected — now pick a check-out date, or drag across dates to select a range.",
        "booking.widget.guests": "Guests",
        "booking.widget.nightsCount": "{count} night",
        "booking.widget.nightsCountPlural": "{count} nights",
        "booking.widget.oneDate": "1 date",
        "booking.widget.bookNow": "Book now",
        "booking.widget.booking": "Booking…",
        "booking.widget.paymentNote": "Your booking request goes to {store} first — you'll pay securely on the next screen.",
        "booking.review.title": "Leave a review",
        "booking.review.prompt": "How was your experience?",
        "booking.review.rating": "Rating",
        "booking.review.comment": "Comment (optional)",
        "booking.review.submit": "Submit review",
        "booking.review.submitting": "Submitting…",
        "booking.review.thanks": "Thanks for your review!",
        "booking.review.yourReview": "Your review",
        "booking.review.addPhoto": "+ Add a photo",
        "booking.review.uploading": "Uploading…",
        "booking.review.maxPhotos": "Maximum of {count} photos per review.",
        "booking.review.providerReply": "Provider response",
        "calendar.open": "Open",
        "calendar.selected": "Selected",
        "calendar.unavailable": "Unavailable",
        "calendar.dragHint": "Tip: drag across dates to select a range",
        "calendar.loading": "Loading…",
        "calendar.previousMonth": "Previous month",
        "calendar.nextMonth": "Next month",
        "calendar.pastDate": "Past date",
        "calendar.notAvailable": "Not available",

        "footer.status": "System status",
        "footer.tagline": "A regional marketplace connecting buyers, sellers & delivery partners.",

        "auth.welcomeBack": "Welcome back",
        "auth.signInSubtitle": "Sign in to your NEXORA account.",
        "auth.newHere": "New here?",
        "auth.otp.title": "Check your email",
        "auth.otp.description": "We sent a 6-digit code to {email}. Enter it below to finish signing in.",
        "auth.otp.codeLabel": "Verification code",
        "auth.otp.verifyButton": "Verify & sign in",
        "auth.otp.verifying": "Verifying…",
        "auth.otp.useDifferentAccount": "Use a different account",
        "auth.otp.resendCode": "Resend code",
        "auth.otp.resendSuccess": "A new code has been sent.",

        "store.noLogo": "No logo",
        "store.verifiedBadge": "Verified",
        "store.memberSince": "Member since {date}",
        "store.notFoundTitle": "Store not found",
        "store.about": "About",
        "store.deliveryTracked": "Delivery tracked door to door",
        "store.deliveryPickupNote": "This store has a pickup location set, so delivery fees are calculated by distance at checkout.",
        "store.deliveryDefaultNote": "Delivery fees are calculated at checkout.",
        "store.trustSafety": "Trust & safety",
        "store.verifiedSellerTitle": "Verified Seller",
        "store.verifiedSellerHint": "This seller has paid NEXORA's verification fee and passed the Verified Seller review - the same badge shown on their individual products.",
        "store.identityVerifiedTitle": "Identity Verified",
        "store.identityVerifiedHint": "NEXORA reviewed this seller's identity documents before their account was approved to sell - separate from, and required before, the paid Verified Seller badge above.",
        "store.productsTitle": "Products",
        "store.productCountOne": "1 product",
        "store.productCountMany": "{count} products",
        "store.noProductsTitle": "No products yet",
        "store.noProductsHint": "This store hasn't listed anything yet - check back soon.",
        "store.onProduct": "on {product}",

        "reviews.title": "Reviews",
        "reviews.sortLowest": "Lowest rated",
        "reviews.summaryOne": "{rating} average · 1 review",
        "reviews.summaryMany": "{rating} average · {count} reviews",
        "reviews.none": "No reviews yet.",
        "reviews.writeReview": "Write a review",
        "reviews.ratingLabel": "Rating",
        "reviews.starsOne": "1 star",
        "reviews.starsMany": "{count} stars",
        "reviews.commentLabel": "Comment (optional)",
        "reviews.submit": "Submit review",
        "reviews.submitting": "Submitting…",
        "reviews.thanks": "Thanks for your review!",
        "reviews.addPhoto": "+ Add a photo",
        "reviews.uploading": "Uploading…",
        "reviews.maxPhotos": "Maximum of {count} photos per review.",
        "reviews.sellerResponse": "Seller response",
        "reviews.loadMore": "Load more reviews",

        "product.notFoundTitle": "Product not found",
        "product.openFullImage": "Open full-size image",
        "product.noImage": "No image",
        "product.videoTitleOne": "Product video",
        "product.videoTitleMany": "Product videos",
        "product.audioTitle": "Product audio",
        "product.verifiedStore": "Verified store",
        "product.brand": "Brand",
        "product.condition": "Condition",
        "product.category": "Category",
        "product.inStock": "In stock",
        "product.addToCart": "Add to cart",
        "product.outOfStock": "Out of stock",
        "product.messageSeller": "Message {seller}",
        "product.defaultSeller": "seller",
        "product.noDescription": "No description provided.",
        "product.buyerOnlyCart": "Only buyer accounts can add items to a cart.",
        "product.buyerOnlyMessage": "Only buyer accounts can message sellers.",
        "product.addedToCart": "Added to cart.",
        "product.conversationError": "Couldn't start a conversation. Please try again.",
        "product.youMayAlsoLike": "You may also like",

        "wallet.title": "Wallet",
        "wallet.subtitle": "Top up your balance to pay for orders instantly at checkout.",
        "wallet.balance": "Balance",
        "wallet.topUpTitle": "Top up",
        "wallet.mobileMoneyNumber": "Mobile money number",
        "wallet.amount": "Amount",
        "wallet.sending": "Sending…",
        "wallet.topUpButton": "Top up",
        "wallet.transactionHistory": "Transaction history",
        "wallet.noTransactionsTitle": "No wallet transactions yet",
        "wallet.noTransactionsHint": "Top up above to get started, or pay for an order to see activity here.",

        "messages.title": "Messages",
        "messages.searchPlaceholder": "Search conversations…",
        "messages.noMatches": "No conversations match \"{query}\".",
        "messages.emptyTitle": "No messages yet",
        "messages.emptyHintBuyer": "Message a seller from any product page to start a conversation.",
        "messages.emptyHintSeller": "Buyers can message you from your product pages.",
        "messages.noMessagePreview": "No messages yet",
        "messages.reLabel": "Re: {product}",
        "messages.deleteAria": "Delete conversation",
        "messages.deleteButton": "Delete",

        "chat.pageTitle": "Conversation",
        "chat.allMessages": "All messages",
        "chat.search": "Search",
        "chat.searchAria": "Search this conversation",
        "chat.clearChat": "Clear chat",
        "chat.deleteChat": "Delete chat",
        "chat.clearForYou": "Clear for you?",
        "chat.confirmClear": "Yes, clear",
        "chat.clearing": "Clearing…",
        "chat.deleteConversationConfirm": "Delete this chat?",
        "chat.confirmDelete": "Yes, delete",
        "chat.deleting": "Deleting…",
        "chat.noMessages": "No messages here yet.",
        "chat.loadError": "Couldn't load this conversation.",
        "chat.attachmentTooLarge": "Attachments must be under {size}MB",
        "chat.removeAttachment": "Remove attachment",
        "chat.attachFile": "Attach a file",
        "chat.writeMessage": "Write a message…",
        "chat.sending": "Sending…",
        "chat.send": "Send",

        "browse.title": "All products",
        "browse.subtitle": "Everything on NEXORA, across every department.",
        "browse.metaDescription": "Browse every product on NEXORA, across every department.",
        "browse.noProductsHint": "Check back soon as sellers list new products.",

        "seller.orders.title": "Orders",
        "seller.orders.empty": "No orders yet.",
        "seller.orders.payoutPendingTooltip": "This order is paid but the payout to your wallet hasn't gone through yet. Our team has been alerted - contact support if it doesn't clear soon.",
        "seller.orders.payoutPending": "Payout pending",
        "seller.orders.accept": "Accept",
        "seller.orders.reject": "Reject",
        "seller.orders.platformPool": "Platform pool",
        "seller.orders.agentMyTeam": "{name} (my team)",
        "seller.orders.addAgentHint": "Add a delivery agent to your roster to ship Cash on Delivery orders",
        "seller.orders.markShipped": "Mark shipped",
        "seller.orders.markDelivered": "Mark delivered",
        "seller.orders.waitingConfirmation": "Waiting for buyer to confirm receipt & cash payment",

        "common.edit": "Edit",

        "seller.products.title": "Your products",
        "seller.products.newProduct": "+ New product",
        "seller.products.searchPlaceholder": "Search your products…",
        "seller.products.allCategories": "All categories",
        "seller.products.allStatuses": "All statuses",
        "seller.products.active": "Active",
        "seller.products.inactive": "Inactive",
        "seller.products.emptyNoListings": "You haven't listed any products yet.",
        "seller.products.emptyNoMatch": "No products match these filters.",
        "seller.products.selectAllAria": "Select all products on this page",
        "seller.products.selectOneAria": "Select {name}",
        "seller.products.stockSuffix": "stock {count}",
        "seller.products.selectedCount": "{count} selected",
        "seller.products.activateSelected": "Activate selected",
        "seller.products.deactivateSelected": "Deactivate selected",
        "seller.products.clearSelection": "Clear selection",
        "seller.products.deactivate": "Deactivate",
        "seller.products.activate": "Activate",
        "seller.products.itemLabel": "products",

        "seller.services.gateTitle": "Services",
        "seller.services.gateDescription": "Offer bookable services - accommodation, transportation, tours, event spaces and more - from the same NEXORA account you already sell products from.",
        "seller.services.addServicesTitle": "Add Services",
        "seller.services.addServicesHint": "Keep selling products, and start offering services too.",
        "seller.services.switchOnlyTitle": "Switch to Services only",
        "seller.services.switchOnlyHint": "Your store becomes a service provider instead of a product seller.",
        "seller.services.title": "Your services",
        "seller.services.newService": "+ New service",
        "seller.services.emptyNoListings": "You haven't listed any services yet.",
        "seller.services.published": "Published",
        "seller.services.draft": "Draft",
        "seller.services.inactive": "Inactive",
        "seller.services.unpublish": "Unpublish",
        "seller.services.publish": "Publish",
        "seller.services.deactivate": "Deactivate",
        "seller.services.activate": "Activate",

        "seller.store.merchantProductLabel": "Products",
        "seller.store.merchantProductDescription": "List physical products for sale.",
        "seller.store.merchantServiceLabel": "Services",
        "seller.store.merchantServiceDescription": "Offer bookable services - accommodation, transportation, tours, and more.",
        "seller.store.merchantHybridLabel": "Products & Services",
        "seller.store.merchantHybridDescription": "Sell products and offer bookable services from the same store.",
        "seller.store.whatYouSell": "What you sell",
        "seller.store.whatYouSellHint": "Controls which dashboard tabs and pages your store sees - Products, Services, or both.",
        "seller.store.merchantTypeUpdated": "Merchant type updated.",
        "seller.store.title": "Store settings",
        "seller.store.logo": "Logo",
        "seller.store.uploading": "Uploading…",
        "seller.store.changeLogo": "Change logo",
        "seller.store.banner": "Banner",
        "seller.store.changeBanner": "Change banner",
        "seller.store.storeName": "Store name",
        "seller.store.storeTagline": "Store tagline",
        "seller.store.storeTaglineHint": "A short line shown right under your store name — e.g. \"Fresh flavors, delivered fast\".",
        "seller.store.optional": "Optional",
        "seller.store.storeDescription": "Store description",
        "seller.store.storeType": "Store type",
        "seller.store.selectStoreType": "Select a store type…",
        "seller.store.storeTheme": "Store theme",
        "seller.store.storeThemeHint": "Sets the accent color on your public store page.",
        "seller.store.socialLinks": "Social links",
        "seller.store.socialLinksHint": "Shown as icons on your public store page. Leave any blank to hide it.",
        "seller.store.instagramPlaceholder": "Instagram (@handle or link)",
        "seller.store.facebookPlaceholder": "Facebook (page name or link)",
        "seller.store.whatsappPlaceholder": "WhatsApp number",
        "seller.store.businessEmail": "Business email",
        "seller.store.businessPhone": "Business phone",
        "seller.store.country": "Country",
        "seller.store.region": "Region",
        "seller.store.city": "City",
        "seller.store.address": "Address",
        "seller.store.pickupLocationLabel": "Pickup location (for delivery pricing)",
        "seller.store.pickupPlacedHint": "Pin placed — delivery fees for your orders will be priced by distance from here instead of the platform's flat rate.",
        "seller.store.pickupEmptyHint": "Tap the map to drop a pin at your store/warehouse. Without one, deliveries for your orders use the platform's flat rider fee instead of distance-based pricing.",
        "seller.store.settingsSaved": "Store settings saved.",
        "seller.store.saving": "Saving…",
        "seller.store.saveChanges": "Save changes",

        "seller.analytics.statusPending": "Pending",
        "seller.analytics.statusProcessing": "Processing",
        "seller.analytics.statusShipped": "Shipped",
        "seller.analytics.statusDelivered": "Delivered",
        "seller.analytics.statusCancelled": "Cancelled",
        "seller.analytics.title": "Analytics",
        "seller.analytics.feeGateDescription": "Analytics is part of the paid Verified Seller features - pay the one-time fee below to unlock it.",
        "seller.analytics.subtitle": "How {store} is performing.",
        "seller.analytics.grossSales": "Gross sales",
        "seller.analytics.commissionPaid": "Commission paid ({rate}%)",
        "seller.analytics.netEarnings": "Net earnings",
        "seller.analytics.totalOrders": "Total orders",
        "seller.analytics.salesLast30": "Sales - last 30 days",
        "seller.analytics.bar": "Bar",
        "seller.analytics.line": "Line",
        "seller.analytics.bestSellingProducts": "Best-selling products",
        "seller.analytics.noSalesYet": "No sales yet.",
        "seller.analytics.soldSuffix": "{count} sold",
        "seller.analytics.customers": "Customers",
        "seller.analytics.repeatCustomers": "Repeat customers",
        "seller.analytics.advancedAnalytics": "Advanced analytics",
        "seller.analytics.customDateRange": "Custom date range",
        "seller.analytics.start": "Start",
        "seller.analytics.end": "End",
        "seller.analytics.apply": "Apply",
        "seller.analytics.clear": "Clear",
        "seller.analytics.pickBothDates": "Pick both a start and end date.",
        "seller.analytics.endAfterStart": "End date must be after start date.",
        "seller.analytics.couldntLoadRange": "Couldn't load that range.",
        "seller.analytics.weekVsLastWeek": "This week vs last week",
        "seller.analytics.monthVsPrior": "Last 30 days vs prior 30 days",
        "seller.analytics.ordersLabel": "orders",
        "seller.analytics.periodComparisonVisualized": "Period comparison, visualized",
        "seller.analytics.lastWeek": "Last week",
        "seller.analytics.thisWeek": "This week",
        "seller.analytics.prior30d": "Prior 30d",
        "seller.analytics.last30d": "Last 30d",
        "seller.analytics.customPrior": "Custom (prior)",
        "seller.analytics.customSelected": "Custom (selected)",
        "seller.analytics.topCustomers": "Top customers",
        "seller.analytics.preparing": "Preparing…",
        "seller.analytics.exportCustomers": "Export customers ↓",
        "seller.analytics.exportProducts": "Export products ↓",
        "seller.analytics.ordersSuffix": "{count} orders",
        "seller.analytics.sellerLeaderboard": "Seller leaderboard",
        "seller.analytics.leaderboardHint": "Ranked by blended product + service revenue, platform-wide.",
        "seller.analytics.noRankedYet": "No paid orders or bookings yet.",
        "seller.analytics.youOfRanked": "You · of {total} ranked sellers",
        "seller.analytics.notRankedYet": "No paid revenue yet, so you're not ranked.",
        "seller.analytics.bookingRevenue": "Booking revenue",
        "seller.analytics.totalBookings": "Total bookings",
        "seller.analytics.pendingBookings": "Pending bookings",
        "seller.analytics.bookingRevenueLast30": "Booking revenue - last 30 days",
        "seller.analytics.noPaidBookings": "No paid bookings yet.",
        "seller.analytics.bestBookedServices": "Best-booked services",
        "seller.analytics.noBookingsYet": "No bookings yet.",
        "seller.analytics.bookedSuffix": "{count} booked"
    },
    sw: {
        "nav.home": "Nyumbani",
        "nav.dashboard": "Dashibodi",
        "nav.deliveries": "Usafirishaji",
        "nav.admin": "Msimamizi",
        "nav.messages": "Ujumbe",
        "nav.orders": "Maagizo",
        "nav.bookings": "Uhifadhi",
        "nav.disputes": "Migogoro",
        "nav.returns": "Marejesho",
        "nav.saved": "Iliyohifadhiwa",
        "nav.wallet": "Pochi",
        "nav.cart": "Kikapu",
        "nav.account": "Akaunti",
        "nav.browse": "Vinjari vyote",
        "nav.services": "Huduma",
        "nav.signOut": "Toka",
        "nav.signIn": "Ingia",
        "nav.join": "Jiunge",
        "nav.searchPlaceholder": "Tafuta bidhaa, chapa...",
        "nav.search": "Tafuta",
        "nav.go": "Nenda",

        "search.recent": "Utafutaji wa hivi karibuni",
        "search.clearRecent": "Futa",
        "search.resultsFor": "Matokeo ya \"{term}\"",
        "search.resultCountOne": "Matokeo 1",
        "search.resultCountMany": "Matokeo {count}",
        "search.clearSearch": "Futa utafutaji",
        "search.noResultsTitle": "Hakuna matokeo ya \"{term}\"",
        "search.noResultsHint": "Jaribu neno tofauti la utafutaji, angalia tahajia, au vinjari idara badala yake.",
        "search.browseDepartments": "Vinjari idara",
        "search.browseAll": "Vinjari bidhaa zote",

        "filters.minPrice": "Bei ya chini",
        "filters.maxPrice": "Bei ya juu",
        "filters.noLimit": "Hakuna kikomo",
        "filters.store": "Duka",
        "filters.allStores": "Maduka yote",
        "filters.location": "Mahali",
        "filters.allLocations": "Maeneo yote",
        "filters.rating": "Ukadiriaji",
        "filters.anyRating": "Ukadiriaji wowote",
        "filters.andUp": "na zaidi",
        "filters.sortBy": "Panga kwa",
        "filters.sortNewest": "Mpya zaidi",
        "filters.sortPriceLow": "Bei: chini kwenda juu",
        "filters.sortPriceHigh": "Bei: juu kwenda chini",
        "filters.sortRating": "Ukadiriaji wa juu zaidi",
        "filters.clear": "Futa vichujio",

        "products.viewGrid": "Mwonekano wa gridi",
        "products.viewList": "Mwonekano wa orodha",

        "account.title": "Akaunti",
        "account.signedInAs": "Umeingia kama",
        "account.profile": "Wasifu",
        "account.settings": "Mipangilio",
        "account.settingsHint": "Lugha, mandhari, na sarafu vinatumika kote NEXORA papo hapo.",
        "account.language": "Lugha",
        "account.theme": "Mandhari",
        "account.currency": "Sarafu",
        "account.changePassword": "Badilisha nenosiri",
        "account.changePasswordHint": "Kwa usalama wako, tutakutumia msimbo wa uthibitisho kwa barua pepe kabla ya kuweka nenosiri jipya.",
        "account.changePasswordButton": "Badilisha Nenosiri",
        "account.deleteAccount": "Futa akaunti",

        "common.save": "Hifadhi",
        "common.saving": "Inahifadhi…",
        "common.cancel": "Ghairi",
        "common.continue": "Endelea",
        "common.loading": "Inapakia…",
        "common.remove": "Ondoa",
        "common.each": "kila moja",
        "common.total": "Jumla",
        "common.browseMarketplace": "Vinjari soko",
        "common.startShopping": "Anza kununua",
        "common.somethingWentWrong": "Hitilafu imetokea. Tafadhali jaribu tena.",

        "auth.signInTitle": "Ingia",
        "auth.emailLabel": "Barua pepe",
        "auth.passwordLabel": "Nenosiri",
        "auth.signInButton": "Ingia",
        "auth.signingIn": "Inaingia…",
        "auth.noAccount": "Huna akaunti?",
        "auth.registerLink": "Unda moja",
        "auth.forgotPasswordLink": "Umesahau nenosiri?",
        "auth.registerTitle": "Unda akaunti yako",
        "auth.haveAccount": "Tayari una akaunti?",
        "auth.signInLink": "Ingia",
        "auth.registerSubtitle": "Unda akaunti yako ili kuanza kununua, kuuza, au kusafirisha.",
        "auth.firstNameLabel": "Jina la kwanza",
        "auth.lastNameLabel": "Jina la mwisho",
        "auth.phoneLabel": "Simu",
        "auth.phoneHint": "Chagua nchi yako, kisha andika namba yako bila sifuri mwanzoni.",
        "auth.countryCodeLabel": "Msimbo wa nchi",
        "auth.passwordHint": "Angalau herufi 8.",
        "auth.roleLabel": "Nataka kufanya nini",
        "auth.roleBuyer": "Nunua bidhaa",
        "auth.roleSeller": "Uza bidhaa",
        "auth.roleDeliveryAgent": "Safirisha maagizo",
        "auth.roleVerificationHint": "Utaombwa kuthibitisha utambulisho wako katika hatua inayofuata kabla akaunti yako haijaundwa.",
        "auth.termsPrefix": "Nakubali",
        "auth.termsOfService": "Masharti ya Huduma",
        "auth.and": "na",
        "auth.privacyPolicy": "Sera ya Faragha",
        "auth.createAccountButton": "Unda akaunti",
        "auth.creatingAccount": "Inaunda akaunti…",
        "auth.continueToVerification": "Endelea na uthibitisho",
        "auth.termsRequiredError": "Tafadhali kubali Masharti ya Huduma na Sera ya Faragha ili kuendelea.",
        "auth.invalidPhoneError": "Tafadhali ingiza namba sahihi ya simu.",

        "cart.title": "Kikapu chako",
        "cart.empty": "Kikapu chako kiko tupu",
        "cart.loading": "Inapakia kikapu…",
        "cart.checkoutButton": "Endelea kulipia",

        "checkout.title": "Kulipia",
        "checkout.placeOrderButton": "Weka agizo",
        "checkout.placingOrder": "Inaweka agizo…",
        "checkout.streetAddress": "Anwani ya mtaa",
        "checkout.city": "Jiji",
        "checkout.region": "Mkoa",
        "checkout.contactPhone": "Simu ya mawasiliano",
        "checkout.paymentMethod": "Njia ya malipo",
        "checkout.orderSummary": "Muhtasari wa agizo",
        "checkout.buyerProtection.title": "Ulinzi wa Mnunuzi",
        "checkout.buyerProtection.description": "Huongeza muda wa kurejesha bidhaa hadi siku 14 na kuhakikisha marejesho ya pesa endapo kuna tatizo",

        "return.new.pageTitle": "Omba kurejesha bidhaa",
        "return.new.eyebrow": "Ulinzi wa Mnunuzi",
        "return.new.intro": "Tuambie kilichotokea na tutapitia ombi lako.",
        "return.new.itemLabel": "Bidhaa",
        "return.new.wholeOrderOption": "Agizo lote",
        "return.new.reasonLabel": "Sababu",
        "return.new.detailsLabel": "Maelezo (si lazima)",
        "return.new.detailsPlaceholder": "Kitu chochote muuzaji anapaswa kujua",
        "return.new.submit": "Wasilisha ombi la kurejesha",
        "return.new.submitting": "Inawasilisha…",
        "return.new.cancel": "Ghairi",
        "return.new.noOrderSpecified": "Hakuna agizo lililotajwa",
        "return.new.loadErrorTitle": "Imeshindwa kupakia agizo hili",
        "return.new.backToOrders": "Rudi kwenye maagizo",
        "return.reason.damaged_item": "Bidhaa ilifika ikiwa imeharibika",
        "return.reason.wrong_item": "Bidhaa isiyo sahihi ilipokelewa",
        "return.reason.defective_product": "Bidhaa ina kasoro",
        "return.reason.not_as_described": "Si kama ilivyoelezwa",
        "return.reason.changed_mind": "Nimebadilisha nia",
        "return.reason.other": "Nyingine",

        "returns.title": "Marejesho yako",
        "returns.empty": "Hakuna ombi la kurejesha bado",
        "returns.loading": "Inapakia marejesho…",

        "orders.title": "Maagizo yako",
        "orders.empty": "Bado hakuna maagizo",
        "orders.loading": "Inapakia maagizo…",
        "orders.vendorsBadge": "wachuuzi {count}",

        "orderTimeline.placed": "Limewekwa",
        "orderTimeline.processing": "Linachakatwa",
        "orderTimeline.shipped": "Limesafirishwa",
        "orderTimeline.delivered": "Limefika",
        "orderTimeline.cancelled": "Agizo hili limeghairiwa.",

        "delivery.tracking.title": "Ufuatiliaji wa usafirishaji",
        "delivery.tracking.agentEnRoute": "Wakala wako wa usafirishaji yuko njiani",
        "delivery.tracking.awaitingAgent": "Inasubiri wakala wa usafirishaji",
        "delivery.tracking.eta": "Muda unaokadiriwa wa kuwasili",
        "delivery.tracking.viewLive": "Tazama ufuatiliaji wa moja kwa moja",
        "delivery.tracking.live": "Moja kwa moja",
        "delivery.tracking.connecting": "Inaunganisha…",
        "delivery.tracking.reconnecting": "Inaunganisha tena…",
        "delivery.tracking.offline": "Ufuatiliaji haupatikani — angalia muunganisho wako",
        "delivery.tracking.distanceRemaining": "Umbali uliobaki",
        "delivery.tracking.calculating": "Inakokotoa…",
        "delivery.tracking.back": "Rudi kwenye agizo",
        "delivery.tracking.unavailable": "Ufuatiliaji haupatikani kwa sasa",
        "delivery.tracking.pickup": "Mahali pa kuchukua",
        "delivery.tracking.destination": "Anwani ya kufikisha",
        "delivery.tracking.viewFullscreen": "Tazama skrini nzima",
        "delivery.tracking.exitFullscreen": "Toka skrini nzima",
        "delivery.tracking.courierDetails": "Taarifa za wakala",
        "delivery.tracking.messageCourier": "Tuma ujumbe",
        "delivery.tracking.callCourier": "Piga simu",
        "delivery.tracking.timeline.title": "Ratiba ya usafirishaji",
        "delivery.tracking.timeline.assigned": "Wakala amepangwa",
        "delivery.tracking.timeline.picked_up": "Amechukua agizo",
        "delivery.tracking.timeline.in_transit": "Yuko njiani",
        "delivery.tracking.timeline.delivered": "Limefika",
        "delivery.tracking.timeline.failed": "Usafirishaji umeshindwa",

        "delivery.agent.available.empty": "Hakuna maagizo tayari kuchukuliwa kwa sasa. Angalia tena baadaye.",
        "delivery.agent.available.claimed": "Agizo limechukuliwa — litapatikana chini ya Usafirishaji wangu.",
        "delivery.agent.available.claim": "Chukua",
        "delivery.agent.available.claiming": "Inachukua…",
        "delivery.agent.mine.empty": "Bado hujachukua usafirishaji wowote.",
        "delivery.agent.mine.contact": "Mawasiliano",
        "delivery.agent.mine.markPickedUp": "Weka alama limechukuliwa",
        "delivery.agent.mine.markInTransit": "Weka alama liko njiani",
        "delivery.agent.mine.markDelivered": "Weka alama limefika",
        "delivery.agent.mine.reportFailed": "Ripoti kushindwa",
        "delivery.agent.earnings.title": "Mapato",
        "delivery.agent.earnings.subtitle": "Ulichopata kwa kusafirisha kwa NEXORA.",
        "delivery.agent.earnings.totalEarned": "Jumla ya mapato",
        "delivery.agent.earnings.today": "Leo",
        "delivery.agent.earnings.last7Days": "Siku 7 zilizopita",
        "delivery.agent.earnings.last30Days": "Siku 30 zilizopita",
        "delivery.agent.earnings.chartTitle": "Mapato - siku 14 zilizopita",
        "delivery.agent.earnings.deliveriesTotal": "jumla ya usafirishaji",
        "delivery.agent.earnings.recent": "Usafirishaji wa hivi karibuni",
        "delivery.agent.earnings.noRecent": "Bado hakuna usafirishaji uliokamilika.",
        "delivery.agent.earnings.loadError": "Imeshindwa kupakia mapato yako.",
        "delivery.agent.ratings.title": "Ukadiriaji",
        "delivery.agent.ratings.subtitle": "Wanunuzi wamesema nini kuhusu usafirishaji wako.",
        "delivery.agent.ratings.average": "Wastani wa ukadiriaji",
        "delivery.agent.ratings.none": "Bado hakuna ukadiriaji",
        "delivery.agent.ratings.total": "Jumla ya ukadiriaji",
        "delivery.agent.ratings.recent": "Ukadiriaji wa hivi karibuni",
        "delivery.agent.ratings.noRecent": "Bado hakuna ukadiriaji - itaonekana hapa baada ya wanunuzi kukadiria agizo lililofikishwa.",
        "delivery.agent.ratings.loadError": "Imeshindwa kupakia ukadiriaji wako.",

        "dispute.type.damaged_item": "Bidhaa iliyoharibika",
        "dispute.type.delayed_delivery": "Usafirishaji uliochelewa",
        "dispute.type.defective_product": "Bidhaa yenye kasoro",
        "dispute.type.wrong_item": "Bidhaa isiyo sahihi",
        "dispute.type.missing_delivery": "Usafirishaji uliokosekana",
        "dispute.type.other": "Suala lingine",
        "dispute.status.open": "wazi",
        "dispute.status.under_review": "inakaguliwa",
        "dispute.status.resolved": "imetatuliwa",
        "dispute.status.rejected": "imekataliwa",
        "dispute.status.withdrawn": "imeondolewa",

        "dispute.new.eyebrow": "Ripoti tatizo",
        "dispute.new.pageTitle": "Ripoti Tatizo",
        "dispute.new.intro": "Tuambie nini kilichoenda vibaya. Timu yetu itakagua na kuwasiliana na uamuzi.",
        "dispute.new.loadErrorTitle": "Imeshindwa kupakia agizo hilo",
        "dispute.new.noOrderSpecified": "Hakuna agizo lililoainishwa.",
        "dispute.new.backToOrders": "Rudi kwenye maagizo",
        "dispute.new.itemLabel": "Hii inahusu bidhaa gani?",
        "dispute.new.wholeOrderOption": "Agizo lote (mfano: kuchelewa / kukosekana kwa usafirishaji)",
        "dispute.new.typeLabel": "Tatizo ni nini?",
        "dispute.new.selectCategory": "Chagua kategoria",
        "dispute.new.subjectLabel": "Mada",
        "dispute.new.subjectPlaceholder": "mfano: Blenda ilifika ikiwa na mtungi uliovunjika",
        "dispute.new.detailsLabel": "Maelezo",
        "dispute.new.detailsPlaceholder": "Eleza kilichotokea. Unaweza kuambatanisha picha baada ya kuwasilisha.",
        "dispute.new.submitting": "Inawasilisha…",
        "dispute.new.submit": "Wasilisha mgogoro",
        "dispute.new.cancel": "Ghairi",

        "dispute.list.title": "Migogoro yangu",
        "dispute.list.intro": "Ripoti tatizo kwa agizo lolote kutoka kwenye ukurasa wake, na fuatilia matokeo hapa.",
        "dispute.list.empty": "Bado hujawasilisha mgogoro wowote.",
        "dispute.list.goToOrders": "Nenda kwenye maagizo yako",
        "dispute.list.orderPrefix": "Agizo",
        "dispute.list.refundApproved": "Marejesho yameidhinishwa",
        "dispute.list.filed": "Iliwasilishwa",
        "dispute.list.maintenanceTitle": "Migogoro iko chini ya matengenezo",

        "dispute.detail.notFound": "Mgogoro haukupatikana",
        "dispute.detail.eyebrow": "Mgogoro",
        "dispute.detail.onOrder": "Kwenye agizo",
        "dispute.detail.filed": "iliwasilishwa",
        "dispute.detail.evidence": "Ushahidi",
        "dispute.detail.addPhoto": "+ Ongeza picha",
        "dispute.detail.uploading": "Inapakia…",
        "dispute.detail.noPhotos": "Bado hakuna picha zilizoambatanishwa.",
        "dispute.detail.withdraw": "Ondoa mgogoro",
        "dispute.detail.withdrawing": "Inaondoa…",
        "dispute.detail.withdrawConfirm": "Ondoa mgogoro huu? Hili haliwezi kutenduliwa.",
        "dispute.detail.discussion": "Majadiliano",
        "dispute.detail.noMessages": "Bado hakuna ujumbe.",
        "dispute.detail.replyAs": "Jibu kama",
        "dispute.detail.sending": "Inatuma…",
        "dispute.detail.send": "Tuma",
        "dispute.detail.closedForMessages": "Mgogoro huu umefungwa kwa ujumbe mpya.",
        "dispute.detail.resolvedPrefix": "Imetatuliwa",
        "dispute.detail.refundAmount": "Kiasi cha marejesho",
        "dispute.detail.rejected": "Mgogoro umekataliwa",

        "auth.verify.ownerPhotoSeller": "Picha ya mmiliki / selfie",
        "auth.verify.ownerPhotoDelivery": "Picha binafsi / selfie",
        "auth.verify.selfieHint": "Picha wazi ya uso wako.",
        "auth.verify.idDocument": "Kitambulisho cha Taifa au cha Mpiga Kura",
        "auth.verify.idDocumentHint": "Picha au nakala ya hati yoyote.",
        "auth.verify.driversLicense": "Leseni ya udereva",
        "auth.verify.driversLicenseHint": "Picha au nakala ya leseni yako.",
        "auth.verify.uploadRequired": "Tafadhali pakia {label} yako.",
        "auth.verify.idDocumentRequired": "Tafadhali pakia Kitambulisho cha Taifa au cha Mpiga Kura.",
        "auth.verify.plateNumberRequired": "Tafadhali weka namba ya bango la gari lako.",
        "auth.verify.accountCreated": "Akaunti imeundwa",
        "auth.verify.pendingReviewNotice": "Nyaraka zako ziliwasilishwa kwa ukaguzi. Unaweza kuingia sasa — dashibodi yako itaonyesha \"Inasubiri Ukaguzi\" hadi msimamizi athibitishe akaunti yako.",
        "auth.verify.takingToSignIn": "Tunakupeleka kuingia…",
        "auth.verify.title": "Thibitisha utambulisho wako",
        "auth.verify.introSeller": "Wachuuzi lazima wawasilishe nyaraka hizi kabla akaunti yao haijaundwa. Akaunti yako itaonyesha \"Inasubiri Ukaguzi\" hadi msimamizi aithibitishe.",
        "auth.verify.introDeliveryAgent": "Mawakala wa usafirishaji lazima wawasilishe nyaraka hizi kabla akaunti yao haijaundwa. Akaunti yako itaonyesha \"Inasubiri Ukaguzi\" hadi msimamizi aithibitishe.",
        "auth.verify.idDocTypeLabel": "Aina ya kitambulisho",
        "auth.verify.nationalId": "Kitambulisho cha Taifa",
        "auth.verify.voterId": "Kitambulisho cha Mpiga Kura",
        "auth.verify.vehicleTypeLabel": "Aina ya gari",
        "auth.verify.bicycle": "Baiskeli",
        "auth.verify.motorcycle": "Pikipiki",
        "auth.verify.tuktuk": "Bajaji",
        "auth.verify.car": "Gari",
        "auth.verify.van": "Gari dogo la mizigo",
        "auth.verify.truck": "Lori",
        "auth.verify.plateNumberLabel": "Namba ya bango",
        "auth.verify.back": "Rudi",
        "auth.verify.submitting": "Inawasilisha…",
        "auth.verify.submitForReview": "Wasilisha kwa ukaguzi",

        "notifications.title": "Arifa",
        "notifications.empty": "Umepata arifa zote",
        "notifications.markAllRead": "Weka zote kama zimesomwa",

        "booking.title": "Uhifadhi wako",
        "booking.empty": "Bado hakuna uhifadhi",
        "booking.browseServices": "Vinjari huduma",
        "booking.loading": "Inapakia uhifadhi…",
        "booking.reference": "Uhifadhi",
        "booking.created": "Imeundwa {date}",
        "booking.status.pending": "Inasubiri",
        "booking.status.confirmed": "Imethibitishwa",
        "booking.status.active": "Inaendelea",
        "booking.status.completed": "Imekamilika",
        "booking.status.cancelled": "Imeghairiwa",
        "booking.status.refunded": "Imerejeshewa",
        "booking.status.rejected": "Imekataliwa",
        "booking.statusLabel": "Hali",
        "booking.payment": "Malipo",
        "booking.paid": "Imelipwa",
        "booking.unpaid": "Haijalipwa",
        "booking.checkIn": "Kuingia",
        "booking.checkOut": "Kutoka",
        "booking.date": "Tarehe",
        "booking.quantity": "Kiasi",
        "booking.total": "Jumla",
        "booking.confirmButton": "Thibitisha uhifadhi",
        "booking.confirming": "Inathibitisha…",
        "booking.cancelButton": "Ghairi uhifadhi",
        "booking.cancelling": "Inaghairi…",
        "booking.rejectButton": "Kataa uhifadhi",
        "booking.rejecting": "Inakataa…",
        "booking.rejectedMessage": "Uhifadhi umekataliwa.",
        "booking.notFound": "Uhifadhi haukupatikana",
        "booking.backToBookings": "Rudi kwenye uhifadhi",
        "booking.justBookedTitle": "Ombi la uhifadhi limetumwa",
        "booking.justBookedBody": "Tumemjulisha {store} — utapata jibu mara watakapothibitisha.",
        "booking.confirmedMessage": "Uhifadhi umethibitishwa.",
        "booking.cancelledMessage": "Uhifadhi umeghairiwa.",
        "booking.cancelledRefundedMessage": "Uhifadhi umeghairiwa na fedha zimerejeshwa.",
        "booking.payment.title": "Lipia uhifadhi huu",
        "booking.payment.escrowNote": "Malipo yako yanashikiliwa kwa usalama hadi uhifadhi wako ukamilike.",
        "booking.payment.phonePlaceholder": "Nambari ya simu kwa malipo ya pesa za simu",
        "booking.payment.phoneRequired": "Weka nambari ya simu kulipa kwa pesa za simu",
        "booking.payment.payMobileMoney": "Lipa kwa Pesa za Simu",
        "booking.payment.payCard": "Lipa kwa Kadi (Snippe)",
        "booking.payment.payCardMalipopay": "Lipa kwa Kadi (MalipoPay)",
        "booking.payment.payPaypal": "Lipa kwa PayPal",
        "booking.payment.processing": "Inachakata…",
        "booking.payment.redirecting": "Inaelekeza…",
        "booking.payment.checkPhone": "Angalia simu yako kukamilisha malipo.",
        "booking.payment.confirming": "Inathibitisha malipo yako…",
        "booking.payment.success": "Malipo yamefanikiwa.",
        "booking.payment.notCompleted": "Malipo hayakuweza kuthibitishwa. Tafadhali jaribu tena.",
        "booking.payment.stillConfirming": "Bado tunathibitisha malipo yako - hii inaweza kuchukua dakika. Onyesha upya kuangalia hali ya hivi karibuni.",
        "booking.payment.cancelledNotice": "Malipo yamesitishwa - uhifadhi wako bado umehifadhiwa, unaweza kujaribu kulipa tena hapa chini.",
        "booking.progress.title": "Maendeleo ya uhifadhi",
        "booking.progress.pending": "Imeombwa",
        "booking.progress.confirmed": "Imethibitishwa",
        "booking.progress.active": "Inaendelea",
        "booking.progress.completed": "Imekamilika",
        "booking.progress.cancelled": "Uhifadhi huu ulighairiwa.",
        "booking.progress.refunded": "Uhifadhi huu ulirejeshewa fedha.",
        "booking.progress.rejected": "Uhifadhi huu ulikataliwa na mtoa huduma.",
        "booking.seller.title": "Uhifadhi",
        "booking.seller.onlyProviders": "Usimamizi wa uhifadhi ni kwa watoa huduma. Ongeza huduma kwenye duka lako kwanza.",
        "booking.seller.goToServices": "Nenda kwa Huduma",
        "booking.seller.empty": "Bado hakuna uhifadhi.",
        "booking.seller.confirm": "Thibitisha",
        "booking.seller.reject": "Kataa",
        "booking.seller.cancel": "Ghairi",
        "booking.seller.details": "Maelezo",
        "booking.widget.selectDates": "Chagua tarehe za kuingia na kutoka",
        "booking.widget.selectDate": "Chagua tarehe",
        "booking.widget.signInPrompt": "Ingia ili kuhifadhi huduma hii",
        "booking.widget.signIn": "Ingia",
        "booking.widget.checkInSelected": "Kuingia {date} kumechaguliwa — sasa chagua tarehe ya kutoka, au buruta kwenye tarehe kuchagua kipindi.",
        "booking.widget.guests": "Wageni",
        "booking.widget.nightsCount": "Usiku {count}",
        "booking.widget.nightsCountPlural": "Usiku {count}",
        "booking.widget.oneDate": "Tarehe 1",
        "booking.widget.bookNow": "Hifadhi sasa",
        "booking.widget.booking": "Inahifadhi…",
        "booking.widget.paymentNote": "Ombi lako la uhifadhi linaenda kwa {store} kwanza — utalipa kwa usalama kwenye skrini inayofuata.",
        "booking.review.title": "Acha maoni",
        "booking.review.prompt": "Ulipataje huduma hii?",
        "booking.review.rating": "Kiwango",
        "booking.review.comment": "Maoni (si lazima)",
        "booking.review.submit": "Tuma maoni",
        "booking.review.submitting": "Inatuma…",
        "booking.review.thanks": "Asante kwa maoni yako!",
        "booking.review.yourReview": "Maoni yako",
        "booking.review.addPhoto": "+ Ongeza picha",
        "booking.review.uploading": "Inapakia…",
        "booking.review.maxPhotos": "Kiwango cha juu cha picha {count} kwa kila maoni.",
        "booking.review.providerReply": "Jibu la mtoa huduma",
        "calendar.open": "Wazi",
        "calendar.selected": "Imechaguliwa",
        "calendar.unavailable": "Haipatikani",
        "calendar.dragHint": "Kidokezo: buruta kwenye tarehe kuchagua kipindi",
        "calendar.loading": "Inapakia…",
        "calendar.previousMonth": "Mwezi uliopita",
        "calendar.nextMonth": "Mwezi ujao",
        "calendar.pastDate": "Tarehe iliyopita",
        "calendar.notAvailable": "Haipatikani",

        "footer.status": "Hali ya mfumo",
        "footer.tagline": "Soko la kikanda linalounganisha wanunuzi, wauzaji na washirika wa usafirishaji.",

        "auth.welcomeBack": "Karibu tena",
        "auth.signInSubtitle": "Ingia kwenye akaunti yako ya NEXORA.",
        "auth.newHere": "Mgeni hapa?",
        "auth.otp.title": "Angalia barua pepe yako",
        "auth.otp.description": "Tumetuma msimbo wa tarakimu 6 kwa {email}. Uweke hapa chini kumaliza kuingia.",
        "auth.otp.codeLabel": "Msimbo wa uthibitisho",
        "auth.otp.verifyButton": "Thibitisha na uingie",
        "auth.otp.verifying": "Inathibitisha…",
        "auth.otp.useDifferentAccount": "Tumia akaunti nyingine",
        "auth.otp.resendCode": "Tuma msimbo tena",
        "auth.otp.resendSuccess": "Msimbo mpya umetumwa.",

        "store.noLogo": "Hakuna nembo",
        "store.verifiedBadge": "Imethibitishwa",
        "store.memberSince": "Mwanachama tangu {date}",
        "store.notFoundTitle": "Duka halikupatikana",
        "store.about": "Kuhusu",
        "store.deliveryTracked": "Uwasilishaji unafuatiliwa mlangoni",
        "store.deliveryPickupNote": "Duka hili lina eneo la kuchukulia bidhaa lililowekwa, hivyo gharama za uwasilishaji zinahesabiwa kwa umbali wakati wa malipo.",
        "store.deliveryDefaultNote": "Gharama za uwasilishaji zinahesabiwa wakati wa malipo.",
        "store.trustSafety": "Uaminifu na usalama",
        "store.verifiedSellerTitle": "Muuzaji Aliyethibitishwa",
        "store.verifiedSellerHint": "Muuzaji huyu amelipia ada ya uthibitisho ya NEXORA na kupitisha ukaguzi wa Muuzaji Aliyethibitishwa - alama hiyo hiyo inayoonekana kwenye bidhaa zake binafsi.",
        "store.identityVerifiedTitle": "Utambulisho Umethibitishwa",
        "store.identityVerifiedHint": "NEXORA ilikagua nyaraka za utambulisho za muuzaji huyu kabla akaunti yake kuidhinishwa kuuza - jambo tofauti na, na linalohitajika kabla ya, alama ya Muuzaji Aliyethibitishwa inayolipiwa iliyo hapo juu.",
        "store.productsTitle": "Bidhaa",
        "store.productCountOne": "Bidhaa 1",
        "store.productCountMany": "Bidhaa {count}",
        "store.noProductsTitle": "Hakuna bidhaa bado",
        "store.noProductsHint": "Duka hili halijaorodhesha chochote bado - rudi tena hivi karibuni.",
        "store.onProduct": "kwenye {product}",

        "reviews.title": "Maoni",
        "reviews.sortLowest": "Kiwango cha chini kabisa",
        "reviews.summaryOne": "Wastani wa {rating} · maoni 1",
        "reviews.summaryMany": "Wastani wa {rating} · maoni {count}",
        "reviews.none": "Hakuna maoni bado.",
        "reviews.writeReview": "Andika maoni",
        "reviews.ratingLabel": "Kiwango",
        "reviews.starsOne": "Nyota 1",
        "reviews.starsMany": "Nyota {count}",
        "reviews.commentLabel": "Maoni (si lazima)",
        "reviews.submit": "Wasilisha maoni",
        "reviews.submitting": "Inawasilisha…",
        "reviews.thanks": "Asante kwa maoni yako!",
        "reviews.addPhoto": "+ Ongeza picha",
        "reviews.uploading": "Inapakia…",
        "reviews.maxPhotos": "Kiwango cha juu cha picha {count} kwa kila maoni.",
        "reviews.sellerResponse": "Jibu la muuzaji",
        "reviews.loadMore": "Pakia maoni zaidi",

        "product.notFoundTitle": "Bidhaa haikupatikana",
        "product.openFullImage": "Fungua picha kamili",
        "product.noImage": "Hakuna picha",
        "product.videoTitleOne": "Video ya bidhaa",
        "product.videoTitleMany": "Video za bidhaa",
        "product.audioTitle": "Sauti ya bidhaa",
        "product.verifiedStore": "Duka lililothibitishwa",
        "product.brand": "Chapa",
        "product.condition": "Hali",
        "product.category": "Jamii",
        "product.inStock": "Ipo stoo",
        "product.addToCart": "Ongeza kwenye kikapu",
        "product.outOfStock": "Haipo stoo",
        "product.messageSeller": "Tuma ujumbe kwa {seller}",
        "product.defaultSeller": "muuzaji",
        "product.noDescription": "Hakuna maelezo yaliyotolewa.",
        "product.buyerOnlyCart": "Akaunti za wanunuzi pekee ndizo zinaweza kuongeza bidhaa kwenye kikapu.",
        "product.buyerOnlyMessage": "Akaunti za wanunuzi pekee ndizo zinaweza kutuma ujumbe kwa wauzaji.",
        "product.addedToCart": "Imeongezwa kwenye kikapu.",
        "product.conversationError": "Imeshindwa kuanzisha mazungumzo. Tafadhali jaribu tena.",
        "product.youMayAlsoLike": "Huenda ukapenda pia",

        "wallet.title": "Pochi",
        "wallet.subtitle": "Ongeza salio lako ili kulipia maagizo papo hapo wakati wa malipo.",
        "wallet.balance": "Salio",
        "wallet.topUpTitle": "Ongeza salio",
        "wallet.mobileMoneyNumber": "Namba ya pesa za simu",
        "wallet.amount": "Kiasi",
        "wallet.sending": "Inatuma…",
        "wallet.topUpButton": "Ongeza salio",
        "wallet.transactionHistory": "Historia ya miamala",
        "wallet.noTransactionsTitle": "Hakuna miamala ya pochi bado",
        "wallet.noTransactionsHint": "Ongeza salio hapo juu kuanza, au lipia agizo kuona shughuli hapa.",

        "messages.title": "Ujumbe",
        "messages.searchPlaceholder": "Tafuta mazungumzo…",
        "messages.noMatches": "Hakuna mazungumzo yanayolingana na \"{query}\".",
        "messages.emptyTitle": "Hakuna ujumbe bado",
        "messages.emptyHintBuyer": "Tuma ujumbe kwa muuzaji kutoka ukurasa wowote wa bidhaa kuanzisha mazungumzo.",
        "messages.emptyHintSeller": "Wanunuzi wanaweza kukutumia ujumbe kutoka kwenye kurasa zako za bidhaa.",
        "messages.noMessagePreview": "Hakuna ujumbe bado",
        "messages.reLabel": "Kuhusu: {product}",
        "messages.deleteAria": "Futa mazungumzo",
        "messages.deleteButton": "Futa",

        "chat.pageTitle": "Mazungumzo",
        "chat.allMessages": "Ujumbe wote",
        "chat.search": "Tafuta",
        "chat.searchAria": "Tafuta ndani ya mazungumzo haya",
        "chat.clearChat": "Futa mazungumzo",
        "chat.deleteChat": "Futa mazungumzo yote",
        "chat.clearForYou": "Futa kwako?",
        "chat.confirmClear": "Ndiyo, futa",
        "chat.clearing": "Inafuta…",
        "chat.deleteConversationConfirm": "Futa mazungumzo haya?",
        "chat.confirmDelete": "Ndiyo, futa",
        "chat.deleting": "Inafuta…",
        "chat.noMessages": "Hakuna ujumbe hapa bado.",
        "chat.loadError": "Imeshindwa kupakia mazungumzo haya.",
        "chat.attachmentTooLarge": "Viambatanisho lazima viwe chini ya {size}MB",
        "chat.removeAttachment": "Ondoa kiambatanisho",
        "chat.attachFile": "Ambatanisha faili",
        "chat.writeMessage": "Andika ujumbe…",
        "chat.sending": "Inatuma…",
        "chat.send": "Tuma",

        "browse.title": "Bidhaa zote",
        "browse.subtitle": "Kila kitu kwenye NEXORA, katika kila idara.",
        "browse.metaDescription": "Vinjari kila bidhaa kwenye NEXORA, katika kila idara.",
        "browse.noProductsHint": "Rudi tena hivi karibuni wauzaji watakapoorodhesha bidhaa mpya.",

        "seller.orders.title": "Maagizo",
        "seller.orders.empty": "Hakuna maagizo bado.",
        "seller.orders.payoutPendingTooltip": "Agizo hili limelipwa lakini malipo kwenye pochi yako bado hayajakamilika. Timu yetu imearifiwa - wasiliana na msaada kama halijakamilika hivi karibuni.",
        "seller.orders.payoutPending": "Malipo yanasubiri",
        "seller.orders.accept": "Kubali",
        "seller.orders.reject": "Kataa",
        "seller.orders.platformPool": "Kundi la jukwaa",
        "seller.orders.agentMyTeam": "{name} (timu yangu)",
        "seller.orders.addAgentHint": "Ongeza wakala wa usafirishaji kwenye orodha yako ili kusafirisha maagizo ya Malipo ya Kuwasili",
        "seller.orders.markShipped": "Weka alama imesafirishwa",
        "seller.orders.markDelivered": "Weka alama imefikishwa",
        "seller.orders.waitingConfirmation": "Inasubiri mnunuzi athibitishe kupokea na malipo ya fedha taslimu",

        "common.edit": "Hariri",

        "seller.products.title": "Bidhaa zako",
        "seller.products.newProduct": "+ Bidhaa mpya",
        "seller.products.searchPlaceholder": "Tafuta bidhaa zako…",
        "seller.products.allCategories": "Jamii zote",
        "seller.products.allStatuses": "Hali zote",
        "seller.products.active": "Hai",
        "seller.products.inactive": "Haihai",
        "seller.products.emptyNoListings": "Bado hujaorodhesha bidhaa yoyote.",
        "seller.products.emptyNoMatch": "Hakuna bidhaa zinazolingana na vichujio hivi.",
        "seller.products.selectAllAria": "Chagua bidhaa zote kwenye ukurasa huu",
        "seller.products.selectOneAria": "Chagua {name}",
        "seller.products.stockSuffix": "stoo {count}",
        "seller.products.selectedCount": "{count} zimechaguliwa",
        "seller.products.activateSelected": "Washa zilizochaguliwa",
        "seller.products.deactivateSelected": "Zima zilizochaguliwa",
        "seller.products.clearSelection": "Futa uchaguzi",
        "seller.products.deactivate": "Zima",
        "seller.products.activate": "Washa",
        "seller.products.itemLabel": "bidhaa",

        "seller.services.gateTitle": "Huduma",
        "seller.services.gateDescription": "Toa huduma zinazoweza kuhifadhiwa - malazi, usafiri, ziara, maeneo ya matukio na zaidi - kutoka akaunti hiyo hiyo ya NEXORA unayouza nayo bidhaa tayari.",
        "seller.services.addServicesTitle": "Ongeza Huduma",
        "seller.services.addServicesHint": "Endelea kuuza bidhaa, na anza kutoa huduma pia.",
        "seller.services.switchOnlyTitle": "Badilisha kuwa Huduma pekee",
        "seller.services.switchOnlyHint": "Duka lako litakuwa mtoa huduma badala ya muuzaji wa bidhaa.",
        "seller.services.title": "Huduma zako",
        "seller.services.newService": "+ Huduma mpya",
        "seller.services.emptyNoListings": "Bado hujaorodhesha huduma yoyote.",
        "seller.services.published": "Imechapishwa",
        "seller.services.draft": "Rasimu",
        "seller.services.inactive": "Haihai",
        "seller.services.unpublish": "Ondoa uchapishaji",
        "seller.services.publish": "Chapisha",
        "seller.services.deactivate": "Zima",
        "seller.services.activate": "Washa",

        "seller.store.merchantProductLabel": "Bidhaa",
        "seller.store.merchantProductDescription": "Orodhesha bidhaa halisi kwa ajili ya kuuza.",
        "seller.store.merchantServiceLabel": "Huduma",
        "seller.store.merchantServiceDescription": "Toa huduma zinazoweza kuhifadhiwa - malazi, usafiri, ziara, na zaidi.",
        "seller.store.merchantHybridLabel": "Bidhaa na Huduma",
        "seller.store.merchantHybridDescription": "Uza bidhaa na toa huduma zinazoweza kuhifadhiwa kutoka duka moja.",
        "seller.store.whatYouSell": "Unachouza",
        "seller.store.whatYouSellHint": "Inadhibiti ni vichupo na kurasa gani duka lako linaona - Bidhaa, Huduma, au zote mbili.",
        "seller.store.merchantTypeUpdated": "Aina ya biashara imesasishwa.",
        "seller.store.title": "Mipangilio ya duka",
        "seller.store.logo": "Nembo",
        "seller.store.uploading": "Inapakia…",
        "seller.store.changeLogo": "Badilisha nembo",
        "seller.store.banner": "Bango",
        "seller.store.changeBanner": "Badilisha bango",
        "seller.store.storeName": "Jina la duka",
        "seller.store.storeTagline": "Kaulimbiu ya duka",
        "seller.store.storeTaglineHint": "Mstari mfupi unaoonekana chini ya jina la duka lako — mfano \"Ladha safi, zinazofikishwa haraka\".",
        "seller.store.optional": "Si lazima",
        "seller.store.storeDescription": "Maelezo ya duka",
        "seller.store.storeType": "Aina ya duka",
        "seller.store.selectStoreType": "Chagua aina ya duka…",
        "seller.store.storeTheme": "Mandhari ya duka",
        "seller.store.storeThemeHint": "Inaweka rangi kuu kwenye ukurasa wako wa duka wa umma.",
        "seller.store.socialLinks": "Viungo vya mitandao ya kijamii",
        "seller.store.socialLinksHint": "Vinaonekana kama aikoni kwenye ukurasa wako wa duka wa umma. Acha wazi ili kuficha.",
        "seller.store.instagramPlaceholder": "Instagram (@jina au kiungo)",
        "seller.store.facebookPlaceholder": "Facebook (jina la ukurasa au kiungo)",
        "seller.store.whatsappPlaceholder": "Namba ya WhatsApp",
        "seller.store.businessEmail": "Barua pepe ya biashara",
        "seller.store.businessPhone": "Namba ya simu ya biashara",
        "seller.store.country": "Nchi",
        "seller.store.region": "Mkoa",
        "seller.store.city": "Jiji",
        "seller.store.address": "Anwani",
        "seller.store.pickupLocationLabel": "Eneo la kuchukulia bidhaa (kwa bei ya uwasilishaji)",
        "seller.store.pickupPlacedHint": "Pini imewekwa — gharama za uwasilishaji za maagizo yako zitahesabiwa kwa umbali kutoka hapa badala ya kiwango cha kawaida cha jukwaa.",
        "seller.store.pickupEmptyHint": "Gusa ramani kuweka pini kwenye duka/ghala lako. Bila hiyo, uwasilishaji wa maagizo yako utatumia ada ya kawaida ya jukwaa badala ya bei ya umbali.",
        "seller.store.settingsSaved": "Mipangilio ya duka imehifadhiwa.",
        "seller.store.saving": "Inahifadhi…",
        "seller.store.saveChanges": "Hifadhi mabadiliko",

        "seller.analytics.statusPending": "Inasubiri",
        "seller.analytics.statusProcessing": "Inashughulikiwa",
        "seller.analytics.statusShipped": "Imesafirishwa",
        "seller.analytics.statusDelivered": "Imefikishwa",
        "seller.analytics.statusCancelled": "Imeghairiwa",
        "seller.analytics.title": "Uchambuzi",
        "seller.analytics.feeGateDescription": "Uchambuzi ni sehemu ya vipengele vinavyolipiwa vya Muuzaji Aliyethibitishwa - lipa ada ya mara moja hapo chini kuufungua.",
        "seller.analytics.subtitle": "Jinsi {store} inavyofanya kazi.",
        "seller.analytics.grossSales": "Mauzo ghafi",
        "seller.analytics.commissionPaid": "Kamisheni iliyolipwa ({rate}%)",
        "seller.analytics.netEarnings": "Mapato halisi",
        "seller.analytics.totalOrders": "Jumla ya maagizo",
        "seller.analytics.salesLast30": "Mauzo - siku 30 zilizopita",
        "seller.analytics.bar": "Baa",
        "seller.analytics.line": "Mstari",
        "seller.analytics.bestSellingProducts": "Bidhaa zinazouzwa zaidi",
        "seller.analytics.noSalesYet": "Hakuna mauzo bado.",
        "seller.analytics.soldSuffix": "{count} zimeuzwa",
        "seller.analytics.customers": "Wateja",
        "seller.analytics.repeatCustomers": "Wateja wanaorudia",
        "seller.analytics.advancedAnalytics": "Uchambuzi wa kina",
        "seller.analytics.customDateRange": "Kipindi maalum cha tarehe",
        "seller.analytics.start": "Mwanzo",
        "seller.analytics.end": "Mwisho",
        "seller.analytics.apply": "Tumia",
        "seller.analytics.clear": "Futa",
        "seller.analytics.pickBothDates": "Chagua tarehe ya mwanzo na mwisho.",
        "seller.analytics.endAfterStart": "Tarehe ya mwisho lazima iwe baada ya ya mwanzo.",
        "seller.analytics.couldntLoadRange": "Imeshindwa kupakia kipindi hicho.",
        "seller.analytics.weekVsLastWeek": "Wiki hii dhidi ya wiki iliyopita",
        "seller.analytics.monthVsPrior": "Siku 30 zilizopita dhidi ya siku 30 kabla yake",
        "seller.analytics.ordersLabel": "maagizo",
        "seller.analytics.periodComparisonVisualized": "Ulinganisho wa vipindi, kwa picha",
        "seller.analytics.lastWeek": "Wiki iliyopita",
        "seller.analytics.thisWeek": "Wiki hii",
        "seller.analytics.prior30d": "Siku 30 kabla",
        "seller.analytics.last30d": "Siku 30 zilizopita",
        "seller.analytics.customPrior": "Maalum (kabla)",
        "seller.analytics.customSelected": "Maalum (iliyochaguliwa)",
        "seller.analytics.topCustomers": "Wateja bora",
        "seller.analytics.preparing": "Inaandaa…",
        "seller.analytics.exportCustomers": "Hamisha wateja ↓",
        "seller.analytics.exportProducts": "Hamisha bidhaa ↓",
        "seller.analytics.ordersSuffix": "maagizo {count}",
        "seller.analytics.sellerLeaderboard": "Ubao wa wauzaji bora",
        "seller.analytics.leaderboardHint": "Imepangwa kwa mapato ya pamoja ya bidhaa na huduma, kote jukwaani.",
        "seller.analytics.noRankedYet": "Hakuna maagizo au uhifadhi uliolipwa bado.",
        "seller.analytics.youOfRanked": "Wewe · kati ya wauzaji {total} waliopangwa",
        "seller.analytics.notRankedYet": "Hakuna mapato yaliyolipwa bado, hivyo hujapangwa.",
        "seller.analytics.bookingRevenue": "Mapato ya uhifadhi",
        "seller.analytics.totalBookings": "Jumla ya uhifadhi",
        "seller.analytics.pendingBookings": "Uhifadhi unaosubiri",
        "seller.analytics.bookingRevenueLast30": "Mapato ya uhifadhi - siku 30 zilizopita",
        "seller.analytics.noPaidBookings": "Hakuna uhifadhi uliolipwa bado.",
        "seller.analytics.bestBookedServices": "Huduma zinazohifadhiwa zaidi",
        "seller.analytics.noBookingsYet": "Hakuna uhifadhi bado.",
        "seller.analytics.bookedSuffix": "{count} zimehifadhiwa"
    }
};

const loadStoredLanguage = () => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return DICTIONARY[stored] ? stored : "en";
};

export function LanguageProvider({ children }) {
    const [language, setLanguageState] = useState(loadStoredLanguage);

    // Phase 1 (Remediation, E4): keep utils/format.js's date formatters
    // in sync with the active language so `sw` renders dates via the
    // "sw-TZ" locale instead of always falling back to "en-GB" - see the
    // comment above setFormatLocale for why this is a module-level sync
    // rather than a formatDate(...) argument.
    useEffect(() => {
        setFormatLocale(language);
    }, [language]);

    const setLanguage = useCallback((next) => {
        if (!DICTIONARY[next]) return;
        localStorage.setItem(STORAGE_KEY, next);
        setLanguageState(next);
    }, []);

    const syncFromProfile = useCallback((profileLanguage) => {
        if (!DICTIONARY[profileLanguage]) return;
        if (localStorage.getItem(STORAGE_KEY)) return;
        setLanguage(profileLanguage);
    }, [setLanguage]);

   
    const t = useCallback((key, params) => {
        const template = DICTIONARY[language]?.[key] || DICTIONARY.en[key] || key;
        if (!params) return template;
        return template.replace(/\{(\w+)\}/g, (match, k) => (
            params[k] !== undefined && params[k] !== null ? String(params[k]) : ""
        ));
    }, [language]);

    const value = useMemo(
        () => ({ language, setLanguage, syncFromProfile, t }),
        [language, setLanguage, syncFromProfile, t]
    );

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
