import { createContext, useContext, useState, useCallback, useMemo, useEffect } from "react";
import { setFormatLocale } from "../utils/format";

const LanguageContext = createContext(null);

const STORAGE_KEY = "nexora_language";
export const LANGUAGES = [
    { code: "en", label: "English" },
    { code: "sw", label: "Kiswahili" }
];


export const DICTIONARY = {
    en: {
        "nav.home": "Home",
        "nav.dashboard": "Dashboard",
        "nav.deliveries": "Deliveries",
        "nav.admin": "Admin",
        "nav.messages": "Messages",
        "nav.orders": "Orders",
        "nav.bookings": "Bookings",
        "nav.disputes": "Disputes",
        "nav.returns": "Returns",
        "nav.saved": "Saved",
        "nav.wallet": "Wallet",
        "nav.cart": "Cart",
        "nav.account": "Account",
        "nav.browse": "Browse all",
        "nav.services": "Services",
        "nav.signOut": "Sign out",
        "nav.signIn": "Sign in",
        "nav.join": "Join",
        "nav.searchPlaceholder": "Search products, brands...",
        "nav.search": "Search",
        "nav.go": "Go",

        "search.recent": "Recent searches",
        "search.clearRecent": "Clear",
        "search.resultsFor": "Results for \"{term}\"",
        "search.resultCountOne": "1 result",
        "search.resultCountMany": "{count} results",
        "search.clearSearch": "Clear search",
        "search.noResultsTitle": "No results for \"{term}\"",
        "search.noResultsHint": "Try a different search term, check your spelling, or browse a department instead.",
        "search.browseDepartments": "Browse departments",
        "search.browseAll": "Browse all products",

        "filters.minPrice": "Min price",
        "filters.maxPrice": "Max price",
        "filters.noLimit": "No limit",
        "filters.store": "Store",
        "filters.allStores": "All stores",
        "filters.location": "Location",
        "filters.allLocations": "All locations",
        "filters.rating": "Rating",
        "filters.anyRating": "Any rating",
        "filters.andUp": "& up",
        "filters.sortBy": "Sort by",
        "filters.sortNewest": "Newest",
        "filters.sortPriceLow": "Price: low to high",
        "filters.sortPriceHigh": "Price: high to low",
        "filters.sortRating": "Highest rated",
        "filters.clear": "Clear filters",

        "products.viewGrid": "Grid view",
        "products.viewList": "List view",

        "account.title": "Account",
        "account.signedInAs": "Signed in as",
        "account.profile": "Profile",
        "account.settings": "Settings",
        "account.settingsHint": "Language, theme, and currency apply across NEXORA instantly.",
        "account.language": "Language",
        "account.theme": "Theme",
        "account.currency": "Currency",
        "account.changePassword": "Change password",
        "account.changePasswordHint": "For your security, we'll email you a verification code before you can set a new password.",
        "account.changePasswordButton": "Change Password",
        "account.deleteAccount": "Delete account",

        "common.save": "Save",
        "common.saving": "Saving…",
        "common.cancel": "Cancel",
        "common.continue": "Continue",
        "common.loading": "Loading…",
        "common.remove": "Remove",
        "common.each": "each",
        "common.total": "Total",
        "common.browseMarketplace": "Browse the marketplace",
        "common.startShopping": "Start shopping",
        "common.somethingWentWrong": "Something went wrong. Please try again.",

        "auth.signInTitle": "Sign in",
        "auth.emailLabel": "Email",
        "auth.passwordLabel": "Password",
        "auth.signInButton": "Sign in",
        "auth.signingIn": "Signing in…",
        "auth.noAccount": "Don't have an account?",
        "auth.registerLink": "Create one",
        "auth.forgotPasswordLink": "Forgot your password?",
        "auth.registerTitle": "Create your account",
        "auth.haveAccount": "Already have an account?",
        "auth.signInLink": "Sign in",
        "auth.registerSubtitle": "Create your account to start buying, selling, or delivering.",
        "auth.firstNameLabel": "First name",
        "auth.lastNameLabel": "Last name",
        "auth.phoneLabel": "Phone",
        "auth.phoneHint": "Choose your country, then enter your number without the leading 0.",
        "auth.countryCodeLabel": "Country code",
        "auth.passwordHint": "At least 8 characters.",
        "auth.roleLabel": "I want to",
        "auth.roleBuyer": "Buy products",
        "auth.roleSeller": "Sell products",
        "auth.roleDeliveryAgent": "Deliver orders",
        "auth.roleVerificationHint": "You'll be asked to verify your identity on the next step before your account is created.",
        "auth.termsPrefix": "I agree to NEXORA's",
        "auth.termsOfService": "Terms of Service",
        "auth.and": "and",
        "auth.privacyPolicy": "Privacy Policy",
        "auth.createAccountButton": "Create account",
        "auth.creatingAccount": "Creating account…",
        "auth.continueToVerification": "Continue to verification",
        "auth.termsRequiredError": "Please accept the Terms of Service and Privacy Policy to continue.",
        "auth.invalidPhoneError": "Please enter a valid phone number.",

        "cart.title": "Your cart",
        "cart.empty": "Your cart is empty",
        "cart.loading": "Loading cart…",
        "cart.checkoutButton": "Proceed to checkout",

        "checkout.title": "Checkout",
        "checkout.placeOrderButton": "Place order",
        "checkout.placingOrder": "Placing order…",
        "checkout.streetAddress": "Street address",
        "checkout.city": "City",
        "checkout.region": "Region",
        "checkout.contactPhone": "Contact phone",
        "checkout.paymentMethod": "Payment method",
        "checkout.orderSummary": "Order summary",
        "checkout.buyerProtection.title": "Buyer Protection",
        "checkout.buyerProtection.description": "Extends your return window to 14 days and guarantees a refund if something goes wrong",

        "return.new.pageTitle": "Request a return",
        "return.new.eyebrow": "Buyer Protection",
        "return.new.intro": "Tell us what happened and we'll review your request.",
        "return.new.itemLabel": "Item",
        "return.new.wholeOrderOption": "Whole order",
        "return.new.reasonLabel": "Reason",
        "return.new.detailsLabel": "Details (optional)",
        "return.new.detailsPlaceholder": "Anything the seller should know",
        "return.new.submit": "Submit return request",
        "return.new.submitting": "Submitting…",
        "return.new.cancel": "Cancel",
        "return.new.noOrderSpecified": "No order specified",
        "return.new.loadErrorTitle": "Couldn't load this order",
        "return.new.backToOrders": "Back to orders",
        "return.reason.damaged_item": "Item arrived damaged",
        "return.reason.wrong_item": "Wrong item received",
        "return.reason.defective_product": "Product is defective",
        "return.reason.not_as_described": "Not as described",
        "return.reason.changed_mind": "Changed my mind",
        "return.reason.other": "Other",

        "returns.title": "Your returns",
        "returns.empty": "No return requests yet",
        "returns.loading": "Loading returns…",

        "orders.title": "Your orders",
        "orders.empty": "No orders yet",
        "orders.loading": "Loading orders…",
        "orders.vendorsBadge": "{count} vendors",

        "orderTimeline.placed": "Placed",
        "orderTimeline.processing": "Processing",
        "orderTimeline.shipped": "Shipped",
        "orderTimeline.delivered": "Delivered",
        "orderTimeline.cancelled": "This order was cancelled.",

        "delivery.tracking.title": "Delivery tracking",
        "delivery.tracking.agentEnRoute": "Your delivery agent is on the way",
        "delivery.tracking.awaitingAgent": "Waiting for a delivery agent",
        "delivery.tracking.eta": "Estimated arrival",
        "delivery.tracking.viewLive": "View live tracking",
        "delivery.tracking.live": "Live",
        "delivery.tracking.connecting": "Connecting…",
        "delivery.tracking.reconnecting": "Reconnecting…",
        "delivery.tracking.offline": "Tracking unavailable — check your connection",
        "delivery.tracking.distanceRemaining": "Distance remaining",
        "delivery.tracking.calculating": "Calculating…",
        "delivery.tracking.back": "Back to order",
        "delivery.tracking.unavailable": "Tracking unavailable",        "delivery.tracking.pickup": "Pickup",
        "delivery.tracking.destination": "Destination",
        "delivery.tracking.viewFullscreen": "View fullscreen",
        "delivery.tracking.exitFullscreen": "Exit fullscreen",
        "delivery.tracking.courierDetails": "Courier details",
        "delivery.tracking.messageCourier": "Message",
        "delivery.tracking.callCourier": "Call",
        "delivery.tracking.timeline.title": "Delivery timeline",
        "delivery.tracking.timeline.assigned": "Agent assigned",
        "delivery.tracking.timeline.picked_up": "Picked up",
        "delivery.tracking.timeline.in_transit": "On the way",
        "delivery.tracking.timeline.delivered": "Delivered",
        "delivery.tracking.timeline.failed": "Delivery failed",

        "delivery.agent.available.empty": "No orders ready for pickup right now. Check back soon.",
        "delivery.agent.available.claimed": "Order claimed — find it under My deliveries.",
        "delivery.agent.available.claim": "Claim",
        "delivery.agent.available.claiming": "Claiming…",
        "delivery.agent.mine.empty": "You haven't claimed any deliveries yet.",
        "delivery.agent.mine.contact": "Contact",
        "delivery.agent.mine.markPickedUp": "Mark picked up",
        "delivery.agent.mine.markInTransit": "Mark in transit",
        "delivery.agent.mine.markDelivered": "Mark delivered",
        "delivery.agent.mine.reportFailed": "Report failed",
        "delivery.agent.earnings.title": "Earnings",
        "delivery.agent.earnings.subtitle": "What you've earned delivering for NEXORA.",
        "delivery.agent.earnings.totalEarned": "Total earned",
        "delivery.agent.earnings.today": "Today",
        "delivery.agent.earnings.last7Days": "Last 7 days",
        "delivery.agent.earnings.last30Days": "Last 30 days",
        "delivery.agent.earnings.chartTitle": "Earnings - last 14 days",
        "delivery.agent.earnings.deliveriesTotal": "deliveries total",
        "delivery.agent.earnings.recent": "Recent deliveries",
        "delivery.agent.earnings.noRecent": "No completed deliveries yet.",
        "delivery.agent.earnings.loadError": "Couldn't load your earnings.",
        "delivery.agent.ratings.title": "Ratings",
        "delivery.agent.ratings.subtitle": "What buyers have said about your deliveries.",
        "delivery.agent.ratings.average": "Average rating",
        "delivery.agent.ratings.none": "No ratings yet",
        "delivery.agent.ratings.total": "Total ratings",
        "delivery.agent.ratings.recent": "Recent ratings",
        "delivery.agent.ratings.noRecent": "No ratings yet - they'll show up here after buyers rate a delivered order.",
        "delivery.agent.ratings.loadError": "Couldn't load your ratings.",

        "dispute.type.damaged_item": "Damaged item",
        "dispute.type.delayed_delivery": "Delayed delivery",
        "dispute.type.defective_product": "Defective product",
        "dispute.type.wrong_item": "Wrong item",
        "dispute.type.missing_delivery": "Missing delivery",
        "dispute.type.other": "Other issue",
        "dispute.status.open": "open",
        "dispute.status.under_review": "under review",
        "dispute.status.resolved": "resolved",
        "dispute.status.rejected": "rejected",
        "dispute.status.withdrawn": "withdrawn",

        "dispute.new.eyebrow": "Report a problem",
        "dispute.new.pageTitle": "Report a Problem",
        "dispute.new.intro": "Tell us what went wrong. Our team will review it and reach out with a decision.",
        "dispute.new.loadErrorTitle": "Couldn't load that order",
        "dispute.new.noOrderSpecified": "No order was specified.",
        "dispute.new.backToOrders": "Back to orders",
        "dispute.new.itemLabel": "Which item is this about?",
        "dispute.new.wholeOrderOption": "The whole order (e.g. delayed / missing delivery)",
        "dispute.new.typeLabel": "What's the issue?",
        "dispute.new.selectCategory": "Select a category",
        "dispute.new.subjectLabel": "Subject",
        "dispute.new.subjectPlaceholder": "e.g. Blender arrived with a cracked jug",
        "dispute.new.detailsLabel": "Details",
        "dispute.new.detailsPlaceholder": "Describe what happened. You can attach photos after submitting.",
        "dispute.new.submitting": "Submitting…",
        "dispute.new.submit": "Submit dispute",
        "dispute.new.cancel": "Cancel",

        "dispute.list.title": "My disputes",
        "dispute.list.intro": "Report a problem with any order from its order page, and track the outcome here.",
        "dispute.list.empty": "You haven't filed any disputes.",
        "dispute.list.goToOrders": "Go to your orders",
        "dispute.list.orderPrefix": "Order",
        "dispute.list.refundApproved": "Refund approved",
        "dispute.list.filed": "Filed",
        "dispute.list.maintenanceTitle": "Disputes is under maintenance",

        "dispute.detail.notFound": "Dispute not found",
        "dispute.detail.eyebrow": "Dispute",
        "dispute.detail.onOrder": "On order",
        "dispute.detail.filed": "filed",
        "dispute.detail.evidence": "Evidence",
        "dispute.detail.addPhoto": "+ Add photo",
        "dispute.detail.uploading": "Uploading…",
        "dispute.detail.noPhotos": "No photos attached yet.",
        "dispute.detail.withdraw": "Withdraw dispute",
        "dispute.detail.withdrawing": "Withdrawing…",
        "dispute.detail.withdrawConfirm": "Withdraw this dispute? This can't be undone.",
        "dispute.detail.discussion": "Discussion",
        "dispute.detail.noMessages": "No messages yet.",
        "dispute.detail.replyAs": "Reply as",
        "dispute.detail.sending": "Sending…",
        "dispute.detail.send": "Send",
        "dispute.detail.closedForMessages": "This dispute is closed for new messages.",
        "dispute.detail.resolvedPrefix": "Resolved",
        "dispute.detail.refundAmount": "Refund amount",
        "dispute.detail.rejected": "Dispute rejected",

        "auth.verify.ownerPhotoSeller": "Owner photo / selfie",
        "auth.verify.ownerPhotoDelivery": "Personal photo / selfie",
        "auth.verify.selfieHint": "A clear photo of your face.",
        "auth.verify.idDocument": "National ID or Voter ID",
        "auth.verify.idDocumentHint": "A photo or scan of either document.",
        "auth.verify.driversLicense": "Driver's license",
        "auth.verify.driversLicenseHint": "A photo or scan of your license.",
        "auth.verify.uploadRequired": "Please upload your {label}.",
        "auth.verify.idDocumentRequired": "Please upload your National ID or Voter ID.",
        "auth.verify.plateNumberRequired": "Please enter your vehicle's plate number.",
        "auth.verify.accountCreated": "Account created",
        "auth.verify.pendingReviewNotice": "Your documents were submitted for review. You can sign in now — your dashboard will show \"Pending Review\" until an admin approves your account.",
        "auth.verify.takingToSignIn": "Taking you to sign in…",
        "auth.verify.title": "Verify your identity",
        "auth.verify.introSeller": "Sellers must submit these documents before their account is created. Your account will show as \"Pending Review\" until an admin approves it.",
        "auth.verify.introDeliveryAgent": "Delivery agents must submit these documents before their account is created. Your account will show as \"Pending Review\" until an admin approves it.",
        "auth.verify.idDocTypeLabel": "ID document type",
        "auth.verify.nationalId": "National ID",
        "auth.verify.voterId": "Voter ID",
        "auth.verify.vehicleTypeLabel": "Vehicle type",
        "auth.verify.bicycle": "Bicycle",
        "auth.verify.motorcycle": "Motorcycle",
        "auth.verify.tuktuk": "Tuk-tuk (Bajaji)",
        "auth.verify.car": "Car",
        "auth.verify.van": "Van",
        "auth.verify.truck": "Truck",
        "auth.verify.plateNumberLabel": "Plate number",
        "auth.verify.back": "Back",
        "auth.verify.submitting": "Submitting…",
        "auth.verify.submitForReview": "Submit for review",

        "notifications.title": "Notifications",
        "notifications.empty": "You're all caught up",
        "notifications.markAllRead": "Mark all as read",

        "booking.title": "Your bookings",
        "booking.empty": "No bookings yet",
        "booking.browseServices": "Browse services",
        "booking.loading": "Loading bookings…",
        "booking.reference": "Booking",
        "booking.created": "Created {date}",
        "booking.status.pending": "Pending",
        "booking.status.confirmed": "Confirmed",
        "booking.status.active": "Active",
        "booking.status.completed": "Completed",
        "booking.status.cancelled": "Cancelled",
        "booking.status.refunded": "Refunded",
        "booking.status.rejected": "Rejected",
        "booking.statusLabel": "Status",
        "booking.payment": "Payment",
        "booking.paid": "Paid",
        "booking.unpaid": "Unpaid",
        "booking.checkIn": "Check-in",
        "booking.checkOut": "Check-out",
        "booking.date": "Date",
        "booking.quantity": "Quantity",
        "booking.total": "Total",
        "booking.confirmButton": "Confirm booking",
        "booking.confirming": "Confirming…",
        "booking.cancelButton": "Cancel booking",
        "booking.cancelling": "Cancelling…",
        "booking.rejectButton": "Decline booking",
        "booking.rejecting": "Declining…",
        "booking.rejectedMessage": "Booking declined.",
        "booking.notFound": "Booking not found",
        "booking.backToBookings": "Back to bookings",
        "booking.justBookedTitle": "Booking request sent",
        "booking.justBookedBody": "We've notified {store} — you'll hear back once they confirm.",
        "booking.confirmedMessage": "Booking confirmed.",
        "booking.cancelledMessage": "Booking cancelled.",
        "booking.cancelledRefundedMessage": "Booking cancelled and refunded.",
        "booking.payment.title": "Pay for this booking",
        "booking.payment.escrowNote": "Your payment is held securely until your booking is complete.",
        "booking.payment.phonePlaceholder": "Phone number for mobile money",
        "booking.payment.phoneRequired": "Enter a phone number to pay by mobile money",
        "booking.payment.payMobileMoney": "Pay with Mobile Money",
        "booking.payment.payCard": "Pay with Card (Snippe)",
        "booking.payment.payCardMalipopay": "Pay with Card (MalipoPay)",
        "booking.payment.payPaypal": "Pay with PayPal",
        "booking.payment.processing": "Processing…",
        "booking.payment.redirecting": "Redirecting…",
        "booking.payment.checkPhone": "Check your phone to complete the payment.",
        "booking.payment.confirming": "Confirming your payment…",
        "booking.payment.success": "Payment successful.",
        "booking.payment.notCompleted": "Payment could not be confirmed. Please try again.",
        "booking.payment.stillConfirming": "We're still confirming your payment - this can take a minute. Refresh to check the latest status.",
        "booking.payment.cancelledNotice": "Payment was cancelled - your booking is still saved, you can try paying again below.",
        "booking.progress.title": "Booking progress",
        "booking.progress.pending": "Requested",
        "booking.progress.confirmed": "Confirmed",
        "booking.progress.active": "In progress",
        "booking.progress.completed": "Completed",
        "booking.progress.cancelled": "This booking was cancelled.",
        "booking.progress.refunded": "This booking was refunded.",
        "booking.progress.rejected": "This booking was declined by the provider.",
        "booking.seller.title": "Bookings",
        "booking.seller.onlyProviders": "Bookings management is for service providers. Add services to your store first.",
        "booking.seller.goToServices": "Go to Services",
        "booking.seller.empty": "No bookings yet.",
        "booking.seller.confirm": "Confirm",
        "booking.seller.reject": "Reject",
        "booking.seller.cancel": "Cancel",
        "booking.seller.details": "Details",
        "booking.widget.selectDates": "Select check-in and check-out dates",
        "booking.widget.selectDate": "Select a date",
        "booking.widget.signInPrompt": "Sign in to book this service",
        "booking.widget.signIn": "Sign in",
        "booking.widget.checkInSelected": "Check-in {date} selected — now pick a check-out date, or drag across dates to select a range.",
        "booking.widget.guests": "Guests",
        "booking.widget.nightsCount": "{count} night",
        "booking.widget.nightsCountPlural": "{count} nights",
        "booking.widget.oneDate": "1 date",
        "booking.widget.bookNow": "Book now",
        "booking.widget.booking": "Booking…",
        "booking.widget.paymentNote": "Your booking request goes to {store} first — you'll pay securely on the next screen.",
        "booking.review.title": "Leave a review",
        "booking.review.prompt": "How was your experience?",
        "booking.review.rating": "Rating",
        "booking.review.comment": "Comment (optional)",
        "booking.review.submit": "Submit review",
        "booking.review.submitting": "Submitting…",
        "booking.review.thanks": "Thanks for your review!",
        "booking.review.yourReview": "Your review",
        "booking.review.addPhoto": "+ Add a photo",
        "booking.review.uploading": "Uploading…",
        "booking.review.maxPhotos": "Maximum of {count} photos per review.",
        "booking.review.providerReply": "Provider response",
        "calendar.open": "Open",
        "calendar.selected": "Selected",
        "calendar.unavailable": "Unavailable",
        "calendar.dragHint": "Tip: drag across dates to select a range",
        "calendar.loading": "Loading…",
        "calendar.previousMonth": "Previous month",
        "calendar.nextMonth": "Next month",
        "calendar.pastDate": "Past date",
        "calendar.notAvailable": "Not available",

        "footer.status": "System status",
        "footer.tagline": "A regional marketplace connecting buyers, sellers & delivery partners."
    },
    sw: {
        "nav.home": "Nyumbani",
        "nav.dashboard": "Dashibodi",
        "nav.deliveries": "Usafirishaji",
        "nav.admin": "Msimamizi",
        "nav.messages": "Ujumbe",
        "nav.orders": "Maagizo",
        "nav.bookings": "Uhifadhi",
        "nav.disputes": "Migogoro",
        "nav.returns": "Marejesho",
        "nav.saved": "Iliyohifadhiwa",
        "nav.wallet": "Pochi",
        "nav.cart": "Kikapu",
        "nav.account": "Akaunti",
        "nav.browse": "Vinjari vyote",
        "nav.services": "Huduma",
        "nav.signOut": "Toka",
        "nav.signIn": "Ingia",
        "nav.join": "Jiunge",
        "nav.searchPlaceholder": "Tafuta bidhaa, chapa...",
        "nav.search": "Tafuta",
        "nav.go": "Nenda",

        "search.recent": "Utafutaji wa hivi karibuni",
        "search.clearRecent": "Futa",
        "search.resultsFor": "Matokeo ya \"{term}\"",
        "search.resultCountOne": "Matokeo 1",
        "search.resultCountMany": "Matokeo {count}",
        "search.clearSearch": "Futa utafutaji",
        "search.noResultsTitle": "Hakuna matokeo ya \"{term}\"",
        "search.noResultsHint": "Jaribu neno tofauti la utafutaji, angalia tahajia, au vinjari idara badala yake.",
        "search.browseDepartments": "Vinjari idara",
        "search.browseAll": "Vinjari bidhaa zote",

        "filters.minPrice": "Bei ya chini",
        "filters.maxPrice": "Bei ya juu",
        "filters.noLimit": "Hakuna kikomo",
        "filters.store": "Duka",
        "filters.allStores": "Maduka yote",
        "filters.location": "Mahali",
        "filters.allLocations": "Maeneo yote",
        "filters.rating": "Ukadiriaji",
        "filters.anyRating": "Ukadiriaji wowote",
        "filters.andUp": "na zaidi",
        "filters.sortBy": "Panga kwa",
        "filters.sortNewest": "Mpya zaidi",
        "filters.sortPriceLow": "Bei: chini kwenda juu",
        "filters.sortPriceHigh": "Bei: juu kwenda chini",
        "filters.sortRating": "Ukadiriaji wa juu zaidi",
        "filters.clear": "Futa vichujio",

        "products.viewGrid": "Mwonekano wa gridi",
        "products.viewList": "Mwonekano wa orodha",

        "account.title": "Akaunti",
        "account.signedInAs": "Umeingia kama",
        "account.profile": "Wasifu",
        "account.settings": "Mipangilio",
        "account.settingsHint": "Lugha, mandhari, na sarafu vinatumika kote NEXORA papo hapo.",
        "account.language": "Lugha",
        "account.theme": "Mandhari",
        "account.currency": "Sarafu",
        "account.changePassword": "Badilisha nenosiri",
        "account.changePasswordHint": "Kwa usalama wako, tutakutumia msimbo wa uthibitisho kwa barua pepe kabla ya kuweka nenosiri jipya.",
        "account.changePasswordButton": "Badilisha Nenosiri",
        "account.deleteAccount": "Futa akaunti",

        "common.save": "Hifadhi",
        "common.saving": "Inahifadhi…",
        "common.cancel": "Ghairi",
        "common.continue": "Endelea",
        "common.loading": "Inapakia…",
        "common.remove": "Ondoa",
        "common.each": "kila moja",
        "common.total": "Jumla",
        "common.browseMarketplace": "Vinjari soko",
        "common.startShopping": "Anza kununua",
        "common.somethingWentWrong": "Hitilafu imetokea. Tafadhali jaribu tena.",

        "auth.signInTitle": "Ingia",
        "auth.emailLabel": "Barua pepe",
        "auth.passwordLabel": "Nenosiri",
        "auth.signInButton": "Ingia",
        "auth.signingIn": "Inaingia…",
        "auth.noAccount": "Huna akaunti?",
        "auth.registerLink": "Unda moja",
        "auth.forgotPasswordLink": "Umesahau nenosiri?",
        "auth.registerTitle": "Unda akaunti yako",
        "auth.haveAccount": "Tayari una akaunti?",
        "auth.signInLink": "Ingia",
        "auth.registerSubtitle": "Unda akaunti yako ili kuanza kununua, kuuza, au kusafirisha.",
        "auth.firstNameLabel": "Jina la kwanza",
        "auth.lastNameLabel": "Jina la mwisho",
        "auth.phoneLabel": "Simu",
        "auth.phoneHint": "Chagua nchi yako, kisha andika namba yako bila sifuri mwanzoni.",
        "auth.countryCodeLabel": "Msimbo wa nchi",
        "auth.passwordHint": "Angalau herufi 8.",
        "auth.roleLabel": "Nataka kufanya nini",
        "auth.roleBuyer": "Nunua bidhaa",
        "auth.roleSeller": "Uza bidhaa",
        "auth.roleDeliveryAgent": "Safirisha maagizo",
        "auth.roleVerificationHint": "Utaombwa kuthibitisha utambulisho wako katika hatua inayofuata kabla akaunti yako haijaundwa.",
        "auth.termsPrefix": "Nakubali",
        "auth.termsOfService": "Masharti ya Huduma",
        "auth.and": "na",
        "auth.privacyPolicy": "Sera ya Faragha",
        "auth.createAccountButton": "Unda akaunti",
        "auth.creatingAccount": "Inaunda akaunti…",
        "auth.continueToVerification": "Endelea na uthibitisho",
        "auth.termsRequiredError": "Tafadhali kubali Masharti ya Huduma na Sera ya Faragha ili kuendelea.",
        "auth.invalidPhoneError": "Tafadhali ingiza namba sahihi ya simu.",

        "cart.title": "Kikapu chako",
        "cart.empty": "Kikapu chako kiko tupu",
        "cart.loading": "Inapakia kikapu…",
        "cart.checkoutButton": "Endelea kulipia",

        "checkout.title": "Kulipia",
        "checkout.placeOrderButton": "Weka agizo",
        "checkout.placingOrder": "Inaweka agizo…",
        "checkout.streetAddress": "Anwani ya mtaa",
        "checkout.city": "Jiji",
        "checkout.region": "Mkoa",
        "checkout.contactPhone": "Simu ya mawasiliano",
        "checkout.paymentMethod": "Njia ya malipo",
        "checkout.orderSummary": "Muhtasari wa agizo",
        "checkout.buyerProtection.title": "Ulinzi wa Mnunuzi",
        "checkout.buyerProtection.description": "Huongeza muda wa kurejesha bidhaa hadi siku 14 na kuhakikisha marejesho ya pesa endapo kuna tatizo",

        "return.new.pageTitle": "Omba kurejesha bidhaa",
        "return.new.eyebrow": "Ulinzi wa Mnunuzi",
        "return.new.intro": "Tuambie kilichotokea na tutapitia ombi lako.",
        "return.new.itemLabel": "Bidhaa",
        "return.new.wholeOrderOption": "Agizo lote",
        "return.new.reasonLabel": "Sababu",
        "return.new.detailsLabel": "Maelezo (si lazima)",
        "return.new.detailsPlaceholder": "Kitu chochote muuzaji anapaswa kujua",
        "return.new.submit": "Wasilisha ombi la kurejesha",
        "return.new.submitting": "Inawasilisha…",
        "return.new.cancel": "Ghairi",
        "return.new.noOrderSpecified": "Hakuna agizo lililotajwa",
        "return.new.loadErrorTitle": "Imeshindwa kupakia agizo hili",
        "return.new.backToOrders": "Rudi kwenye maagizo",
        "return.reason.damaged_item": "Bidhaa ilifika ikiwa imeharibika",
        "return.reason.wrong_item": "Bidhaa isiyo sahihi ilipokelewa",
        "return.reason.defective_product": "Bidhaa ina kasoro",
        "return.reason.not_as_described": "Si kama ilivyoelezwa",
        "return.reason.changed_mind": "Nimebadilisha nia",
        "return.reason.other": "Nyingine",

        "returns.title": "Marejesho yako",
        "returns.empty": "Hakuna ombi la kurejesha bado",
        "returns.loading": "Inapakia marejesho…",

        "orders.title": "Maagizo yako",
        "orders.empty": "Bado hakuna maagizo",
        "orders.loading": "Inapakia maagizo…",
        "orders.vendorsBadge": "wachuuzi {count}",

        "orderTimeline.placed": "Limewekwa",
        "orderTimeline.processing": "Linachakatwa",
        "orderTimeline.shipped": "Limesafirishwa",
        "orderTimeline.delivered": "Limefika",
        "orderTimeline.cancelled": "Agizo hili limeghairiwa.",

        "delivery.tracking.title": "Ufuatiliaji wa usafirishaji",
        "delivery.tracking.agentEnRoute": "Wakala wako wa usafirishaji yuko njiani",
        "delivery.tracking.awaitingAgent": "Inasubiri wakala wa usafirishaji",
        "delivery.tracking.eta": "Muda unaokadiriwa wa kuwasili",
        "delivery.tracking.viewLive": "Tazama ufuatiliaji wa moja kwa moja",
        "delivery.tracking.live": "Moja kwa moja",
        "delivery.tracking.connecting": "Inaunganisha…",
        "delivery.tracking.reconnecting": "Inaunganisha tena…",
        "delivery.tracking.offline": "Ufuatiliaji haupatikani — angalia muunganisho wako",
        "delivery.tracking.distanceRemaining": "Umbali uliobaki",
        "delivery.tracking.calculating": "Inakokotoa…",
        "delivery.tracking.back": "Rudi kwenye agizo",
        "delivery.tracking.unavailable": "Ufuatiliaji haupatikani kwa sasa",
        "delivery.tracking.pickup": "Mahali pa kuchukua",
        "delivery.tracking.destination": "Anwani ya kufikisha",
        "delivery.tracking.viewFullscreen": "Tazama skrini nzima",
        "delivery.tracking.exitFullscreen": "Toka skrini nzima",
        "delivery.tracking.courierDetails": "Taarifa za wakala",
        "delivery.tracking.messageCourier": "Tuma ujumbe",
        "delivery.tracking.callCourier": "Piga simu",
        "delivery.tracking.timeline.title": "Ratiba ya usafirishaji",
        "delivery.tracking.timeline.assigned": "Wakala amepangwa",
        "delivery.tracking.timeline.picked_up": "Amechukua agizo",
        "delivery.tracking.timeline.in_transit": "Yuko njiani",
        "delivery.tracking.timeline.delivered": "Limefika",
        "delivery.tracking.timeline.failed": "Usafirishaji umeshindwa",

        "delivery.agent.available.empty": "Hakuna maagizo tayari kuchukuliwa kwa sasa. Angalia tena baadaye.",
        "delivery.agent.available.claimed": "Agizo limechukuliwa — litapatikana chini ya Usafirishaji wangu.",
        "delivery.agent.available.claim": "Chukua",
        "delivery.agent.available.claiming": "Inachukua…",
        "delivery.agent.mine.empty": "Bado hujachukua usafirishaji wowote.",
        "delivery.agent.mine.contact": "Mawasiliano",
        "delivery.agent.mine.markPickedUp": "Weka alama limechukuliwa",
        "delivery.agent.mine.markInTransit": "Weka alama liko njiani",
        "delivery.agent.mine.markDelivered": "Weka alama limefika",
        "delivery.agent.mine.reportFailed": "Ripoti kushindwa",
        "delivery.agent.earnings.title": "Mapato",
        "delivery.agent.earnings.subtitle": "Ulichopata kwa kusafirisha kwa NEXORA.",
        "delivery.agent.earnings.totalEarned": "Jumla ya mapato",
        "delivery.agent.earnings.today": "Leo",
        "delivery.agent.earnings.last7Days": "Siku 7 zilizopita",
        "delivery.agent.earnings.last30Days": "Siku 30 zilizopita",
        "delivery.agent.earnings.chartTitle": "Mapato - siku 14 zilizopita",
        "delivery.agent.earnings.deliveriesTotal": "jumla ya usafirishaji",
        "delivery.agent.earnings.recent": "Usafirishaji wa hivi karibuni",
        "delivery.agent.earnings.noRecent": "Bado hakuna usafirishaji uliokamilika.",
        "delivery.agent.earnings.loadError": "Imeshindwa kupakia mapato yako.",
        "delivery.agent.ratings.title": "Ukadiriaji",
        "delivery.agent.ratings.subtitle": "Wanunuzi wamesema nini kuhusu usafirishaji wako.",
        "delivery.agent.ratings.average": "Wastani wa ukadiriaji",
        "delivery.agent.ratings.none": "Bado hakuna ukadiriaji",
        "delivery.agent.ratings.total": "Jumla ya ukadiriaji",
        "delivery.agent.ratings.recent": "Ukadiriaji wa hivi karibuni",
        "delivery.agent.ratings.noRecent": "Bado hakuna ukadiriaji - itaonekana hapa baada ya wanunuzi kukadiria agizo lililofikishwa.",
        "delivery.agent.ratings.loadError": "Imeshindwa kupakia ukadiriaji wako.",

        "dispute.type.damaged_item": "Bidhaa iliyoharibika",
        "dispute.type.delayed_delivery": "Usafirishaji uliochelewa",
        "dispute.type.defective_product": "Bidhaa yenye kasoro",
        "dispute.type.wrong_item": "Bidhaa isiyo sahihi",
        "dispute.type.missing_delivery": "Usafirishaji uliokosekana",
        "dispute.type.other": "Suala lingine",
        "dispute.status.open": "wazi",
        "dispute.status.under_review": "inakaguliwa",
        "dispute.status.resolved": "imetatuliwa",
        "dispute.status.rejected": "imekataliwa",
        "dispute.status.withdrawn": "imeondolewa",

        "dispute.new.eyebrow": "Ripoti tatizo",
        "dispute.new.pageTitle": "Ripoti Tatizo",
        "dispute.new.intro": "Tuambie nini kilichoenda vibaya. Timu yetu itakagua na kuwasiliana na uamuzi.",
        "dispute.new.loadErrorTitle": "Imeshindwa kupakia agizo hilo",
        "dispute.new.noOrderSpecified": "Hakuna agizo lililoainishwa.",
        "dispute.new.backToOrders": "Rudi kwenye maagizo",
        "dispute.new.itemLabel": "Hii inahusu bidhaa gani?",
        "dispute.new.wholeOrderOption": "Agizo lote (mfano: kuchelewa / kukosekana kwa usafirishaji)",
        "dispute.new.typeLabel": "Tatizo ni nini?",
        "dispute.new.selectCategory": "Chagua kategoria",
        "dispute.new.subjectLabel": "Mada",
        "dispute.new.subjectPlaceholder": "mfano: Blenda ilifika ikiwa na mtungi uliovunjika",
        "dispute.new.detailsLabel": "Maelezo",
        "dispute.new.detailsPlaceholder": "Eleza kilichotokea. Unaweza kuambatanisha picha baada ya kuwasilisha.",
        "dispute.new.submitting": "Inawasilisha…",
        "dispute.new.submit": "Wasilisha mgogoro",
        "dispute.new.cancel": "Ghairi",

        "dispute.list.title": "Migogoro yangu",
        "dispute.list.intro": "Ripoti tatizo kwa agizo lolote kutoka kwenye ukurasa wake, na fuatilia matokeo hapa.",
        "dispute.list.empty": "Bado hujawasilisha mgogoro wowote.",
        "dispute.list.goToOrders": "Nenda kwenye maagizo yako",
        "dispute.list.orderPrefix": "Agizo",
        "dispute.list.refundApproved": "Marejesho yameidhinishwa",
        "dispute.list.filed": "Iliwasilishwa",
        "dispute.list.maintenanceTitle": "Migogoro iko chini ya matengenezo",

        "dispute.detail.notFound": "Mgogoro haukupatikana",
        "dispute.detail.eyebrow": "Mgogoro",
        "dispute.detail.onOrder": "Kwenye agizo",
        "dispute.detail.filed": "iliwasilishwa",
        "dispute.detail.evidence": "Ushahidi",
        "dispute.detail.addPhoto": "+ Ongeza picha",
        "dispute.detail.uploading": "Inapakia…",
        "dispute.detail.noPhotos": "Bado hakuna picha zilizoambatanishwa.",
        "dispute.detail.withdraw": "Ondoa mgogoro",
        "dispute.detail.withdrawing": "Inaondoa…",
        "dispute.detail.withdrawConfirm": "Ondoa mgogoro huu? Hili haliwezi kutenduliwa.",
        "dispute.detail.discussion": "Majadiliano",
        "dispute.detail.noMessages": "Bado hakuna ujumbe.",
        "dispute.detail.replyAs": "Jibu kama",
        "dispute.detail.sending": "Inatuma…",
        "dispute.detail.send": "Tuma",
        "dispute.detail.closedForMessages": "Mgogoro huu umefungwa kwa ujumbe mpya.",
        "dispute.detail.resolvedPrefix": "Imetatuliwa",
        "dispute.detail.refundAmount": "Kiasi cha marejesho",
        "dispute.detail.rejected": "Mgogoro umekataliwa",

        "auth.verify.ownerPhotoSeller": "Picha ya mmiliki / selfie",
        "auth.verify.ownerPhotoDelivery": "Picha binafsi / selfie",
        "auth.verify.selfieHint": "Picha wazi ya uso wako.",
        "auth.verify.idDocument": "Kitambulisho cha Taifa au cha Mpiga Kura",
        "auth.verify.idDocumentHint": "Picha au nakala ya hati yoyote.",
        "auth.verify.driversLicense": "Leseni ya udereva",
        "auth.verify.driversLicenseHint": "Picha au nakala ya leseni yako.",
        "auth.verify.uploadRequired": "Tafadhali pakia {label} yako.",
        "auth.verify.idDocumentRequired": "Tafadhali pakia Kitambulisho cha Taifa au cha Mpiga Kura.",
        "auth.verify.plateNumberRequired": "Tafadhali weka namba ya bango la gari lako.",
        "auth.verify.accountCreated": "Akaunti imeundwa",
        "auth.verify.pendingReviewNotice": "Nyaraka zako ziliwasilishwa kwa ukaguzi. Unaweza kuingia sasa — dashibodi yako itaonyesha \"Inasubiri Ukaguzi\" hadi msimamizi athibitishe akaunti yako.",
        "auth.verify.takingToSignIn": "Tunakupeleka kuingia…",
        "auth.verify.title": "Thibitisha utambulisho wako",
        "auth.verify.introSeller": "Wachuuzi lazima wawasilishe nyaraka hizi kabla akaunti yao haijaundwa. Akaunti yako itaonyesha \"Inasubiri Ukaguzi\" hadi msimamizi aithibitishe.",
        "auth.verify.introDeliveryAgent": "Mawakala wa usafirishaji lazima wawasilishe nyaraka hizi kabla akaunti yao haijaundwa. Akaunti yako itaonyesha \"Inasubiri Ukaguzi\" hadi msimamizi aithibitishe.",
        "auth.verify.idDocTypeLabel": "Aina ya kitambulisho",
        "auth.verify.nationalId": "Kitambulisho cha Taifa",
        "auth.verify.voterId": "Kitambulisho cha Mpiga Kura",
        "auth.verify.vehicleTypeLabel": "Aina ya gari",
        "auth.verify.bicycle": "Baiskeli",
        "auth.verify.motorcycle": "Pikipiki",
        "auth.verify.tuktuk": "Bajaji",
        "auth.verify.car": "Gari",
        "auth.verify.van": "Gari dogo la mizigo",
        "auth.verify.truck": "Lori",
        "auth.verify.plateNumberLabel": "Namba ya bango",
        "auth.verify.back": "Rudi",
        "auth.verify.submitting": "Inawasilisha…",
        "auth.verify.submitForReview": "Wasilisha kwa ukaguzi",

        "notifications.title": "Arifa",
        "notifications.empty": "Umepata arifa zote",
        "notifications.markAllRead": "Weka zote kama zimesomwa",

        "booking.title": "Uhifadhi wako",
        "booking.empty": "Bado hakuna uhifadhi",
        "booking.browseServices": "Vinjari huduma",
        "booking.loading": "Inapakia uhifadhi…",
        "booking.reference": "Uhifadhi",
        "booking.created": "Imeundwa {date}",
        "booking.status.pending": "Inasubiri",
        "booking.status.confirmed": "Imethibitishwa",
        "booking.status.active": "Inaendelea",
        "booking.status.completed": "Imekamilika",
        "booking.status.cancelled": "Imeghairiwa",
        "booking.status.refunded": "Imerejeshewa",
        "booking.status.rejected": "Imekataliwa",
        "booking.statusLabel": "Hali",
        "booking.payment": "Malipo",
        "booking.paid": "Imelipwa",
        "booking.unpaid": "Haijalipwa",
        "booking.checkIn": "Kuingia",
        "booking.checkOut": "Kutoka",
        "booking.date": "Tarehe",
        "booking.quantity": "Kiasi",
        "booking.total": "Jumla",
        "booking.confirmButton": "Thibitisha uhifadhi",
        "booking.confirming": "Inathibitisha…",
        "booking.cancelButton": "Ghairi uhifadhi",
        "booking.cancelling": "Inaghairi…",
        "booking.rejectButton": "Kataa uhifadhi",
        "booking.rejecting": "Inakataa…",
        "booking.rejectedMessage": "Uhifadhi umekataliwa.",
        "booking.notFound": "Uhifadhi haukupatikana",
        "booking.backToBookings": "Rudi kwenye uhifadhi",
        "booking.justBookedTitle": "Ombi la uhifadhi limetumwa",
        "booking.justBookedBody": "Tumemjulisha {store} — utapata jibu mara watakapothibitisha.",
        "booking.confirmedMessage": "Uhifadhi umethibitishwa.",
        "booking.cancelledMessage": "Uhifadhi umeghairiwa.",
        "booking.cancelledRefundedMessage": "Uhifadhi umeghairiwa na fedha zimerejeshwa.",
        "booking.payment.title": "Lipia uhifadhi huu",
        "booking.payment.escrowNote": "Malipo yako yanashikiliwa kwa usalama hadi uhifadhi wako ukamilike.",
        "booking.payment.phonePlaceholder": "Nambari ya simu kwa malipo ya pesa za simu",
        "booking.payment.phoneRequired": "Weka nambari ya simu kulipa kwa pesa za simu",
        "booking.payment.payMobileMoney": "Lipa kwa Pesa za Simu",
        "booking.payment.payCard": "Lipa kwa Kadi (Snippe)",
        "booking.payment.payCardMalipopay": "Lipa kwa Kadi (MalipoPay)",
        "booking.payment.payPaypal": "Lipa kwa PayPal",
        "booking.payment.processing": "Inachakata…",
        "booking.payment.redirecting": "Inaelekeza…",
        "booking.payment.checkPhone": "Angalia simu yako kukamilisha malipo.",
        "booking.payment.confirming": "Inathibitisha malipo yako…",
        "booking.payment.success": "Malipo yamefanikiwa.",
        "booking.payment.notCompleted": "Malipo hayakuweza kuthibitishwa. Tafadhali jaribu tena.",
        "booking.payment.stillConfirming": "Bado tunathibitisha malipo yako - hii inaweza kuchukua dakika. Onyesha upya kuangalia hali ya hivi karibuni.",
        "booking.payment.cancelledNotice": "Malipo yamesitishwa - uhifadhi wako bado umehifadhiwa, unaweza kujaribu kulipa tena hapa chini.",
        "booking.progress.title": "Maendeleo ya uhifadhi",
        "booking.progress.pending": "Imeombwa",
        "booking.progress.confirmed": "Imethibitishwa",
        "booking.progress.active": "Inaendelea",
        "booking.progress.completed": "Imekamilika",
        "booking.progress.cancelled": "Uhifadhi huu ulighairiwa.",
        "booking.progress.refunded": "Uhifadhi huu ulirejeshewa fedha.",
        "booking.progress.rejected": "Uhifadhi huu ulikataliwa na mtoa huduma.",
        "booking.seller.title": "Uhifadhi",
        "booking.seller.onlyProviders": "Usimamizi wa uhifadhi ni kwa watoa huduma. Ongeza huduma kwenye duka lako kwanza.",
        "booking.seller.goToServices": "Nenda kwa Huduma",
        "booking.seller.empty": "Bado hakuna uhifadhi.",
        "booking.seller.confirm": "Thibitisha",
        "booking.seller.reject": "Kataa",
        "booking.seller.cancel": "Ghairi",
        "booking.seller.details": "Maelezo",
        "booking.widget.selectDates": "Chagua tarehe za kuingia na kutoka",
        "booking.widget.selectDate": "Chagua tarehe",
        "booking.widget.signInPrompt": "Ingia ili kuhifadhi huduma hii",
        "booking.widget.signIn": "Ingia",
        "booking.widget.checkInSelected": "Kuingia {date} kumechaguliwa — sasa chagua tarehe ya kutoka, au buruta kwenye tarehe kuchagua kipindi.",
        "booking.widget.guests": "Wageni",
        "booking.widget.nightsCount": "Usiku {count}",
        "booking.widget.nightsCountPlural": "Usiku {count}",
        "booking.widget.oneDate": "Tarehe 1",
        "booking.widget.bookNow": "Hifadhi sasa",
        "booking.widget.booking": "Inahifadhi…",
        "booking.widget.paymentNote": "Ombi lako la uhifadhi linaenda kwa {store} kwanza — utalipa kwa usalama kwenye skrini inayofuata.",
        "booking.review.title": "Acha maoni",
        "booking.review.prompt": "Ulipataje huduma hii?",
        "booking.review.rating": "Kiwango",
        "booking.review.comment": "Maoni (si lazima)",
        "booking.review.submit": "Tuma maoni",
        "booking.review.submitting": "Inatuma…",
        "booking.review.thanks": "Asante kwa maoni yako!",
        "booking.review.yourReview": "Maoni yako",
        "booking.review.addPhoto": "+ Ongeza picha",
        "booking.review.uploading": "Inapakia…",
        "booking.review.maxPhotos": "Kiwango cha juu cha picha {count} kwa kila maoni.",
        "booking.review.providerReply": "Jibu la mtoa huduma",
        "calendar.open": "Wazi",
        "calendar.selected": "Imechaguliwa",
        "calendar.unavailable": "Haipatikani",
        "calendar.dragHint": "Kidokezo: buruta kwenye tarehe kuchagua kipindi",
        "calendar.loading": "Inapakia…",
        "calendar.previousMonth": "Mwezi uliopita",
        "calendar.nextMonth": "Mwezi ujao",
        "calendar.pastDate": "Tarehe iliyopita",
        "calendar.notAvailable": "Haipatikani",

        "footer.status": "Hali ya mfumo",
        "footer.tagline": "Soko la kikanda linalounganisha wanunuzi, wauzaji na washirika wa usafirishaji."
    }
};

const loadStoredLanguage = () => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return DICTIONARY[stored] ? stored : "en";
};

export function LanguageProvider({ children }) {
    const [language, setLanguageState] = useState(loadStoredLanguage);

    // Phase 1 (Remediation, E4): keep utils/format.js's date formatters
    // in sync with the active language so `sw` renders dates via the
    // "sw-TZ" locale instead of always falling back to "en-GB" - see the
    // comment above setFormatLocale for why this is a module-level sync
    // rather than a formatDate(...) argument.
    useEffect(() => {
        setFormatLocale(language);
    }, [language]);

    const setLanguage = useCallback((next) => {
        if (!DICTIONARY[next]) return;
        localStorage.setItem(STORAGE_KEY, next);
        setLanguageState(next);
    }, []);

    const syncFromProfile = useCallback((profileLanguage) => {
        if (!DICTIONARY[profileLanguage]) return;
        if (localStorage.getItem(STORAGE_KEY)) return;
        setLanguage(profileLanguage);
    }, [setLanguage]);

   
    const t = useCallback((key, params) => {
        const template = DICTIONARY[language]?.[key] || DICTIONARY.en[key] || key;
        if (!params) return template;
        return template.replace(/\{(\w+)\}/g, (match, k) => (
            params[k] !== undefined && params[k] !== null ? String(params[k]) : ""
        ));
    }, [language]);

    const value = useMemo(
        () => ({ language, setLanguage, syncFromProfile, t }),
        [language, setLanguage, syncFromProfile, t]
    );

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
